# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_output.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BoltOutput(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 191)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1236, 273))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 9, 2)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 3, 9, 2)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 5, 9, 2)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 0, 7, 9, 3)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 0, 10, 9, 2)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 0, 12, 9, 2)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 14, 9, 2)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 0, 16, 9, 2)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 0, 18, 9, 2)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 0, 20, 9, 2)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 0, 22, 9, 2)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 0, 24, 9, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 9, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 11, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 13, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 15, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 17, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 19, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 21, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 23, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 25, 1, 1)
        self.lbl_mem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem.setFont(font)
        self.lbl_mem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem.setObjectName("lbl_mem")
        self.gridLayout_2.addWidget(self.lbl_mem, 2, 0, 1, 1)
        self.lineEdit_shr = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr.setFont(font)
        self.lineEdit_shr.setReadOnly(True)
        self.lineEdit_shr.setObjectName("lineEdit_shr")
        self.gridLayout_2.addWidget(self.lineEdit_shr, 2, 2, 1, 1)
        self.lineEdit_ber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber.setFont(font)
        self.lineEdit_ber.setReadOnly(True)
        self.lineEdit_ber.setObjectName("lineEdit_ber")
        self.gridLayout_2.addWidget(self.lineEdit_ber, 2, 4, 1, 1)
        self.lineEdit_req = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req.setFont(font)
        self.lineEdit_req.setReadOnly(True)
        self.lineEdit_req.setObjectName("lineEdit_req")
        self.gridLayout_2.addWidget(self.lineEdit_req, 2, 6, 1, 1)
        self.lineEdit_blt_cap = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap.setFont(font)
        self.lineEdit_blt_cap.setReadOnly(True)
        self.lineEdit_blt_cap.setObjectName("lineEdit_blt_cap")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap, 2, 8, 1, 2)
        self.lineEdit_col = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col.setFont(font)
        self.lineEdit_col.setReadOnly(True)
        self.lineEdit_col.setObjectName("lineEdit_col")
        self.gridLayout_2.addWidget(self.lineEdit_col, 2, 11, 1, 1)
        self.lineEdit_row = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setReadOnly(True)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.gridLayout_2.addWidget(self.lineEdit_row, 2, 13, 1, 1)
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch.setFont(font)
        self.lineEdit_pitch.setReadOnly(True)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout_2.addWidget(self.lineEdit_pitch, 2, 15, 1, 1)
        self.lineEdit_gauge = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge.setFont(font)
        self.lineEdit_gauge.setReadOnly(True)
        self.lineEdit_gauge.setObjectName("lineEdit_gauge")
        self.gridLayout_2.addWidget(self.lineEdit_gauge, 2, 17, 1, 1)
        self.lineEdit_end = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end.setFont(font)
        self.lineEdit_end.setReadOnly(True)
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.gridLayout_2.addWidget(self.lineEdit_end, 2, 19, 1, 1)
        self.lineEdit_edge = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge.setFont(font)
        self.lineEdit_edge.setReadOnly(True)
        self.lineEdit_edge.setObjectName("lineEdit_edge")
        self.gridLayout_2.addWidget(self.lineEdit_edge, 2, 21, 1, 1)
        self.lineEdit_tens = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens.setReadOnly(True)
        self.lineEdit_tens.setObjectName("lineEdit_tens")
        self.gridLayout_2.addWidget(self.lineEdit_tens, 2, 23, 1, 1)
        self.lineEdit_block = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block.setReadOnly(True)
        self.lineEdit_block.setObjectName("lineEdit_block")
        self.gridLayout_2.addWidget(self.lineEdit_block, 2, 25, 1, 1)
        self.lbl_mem2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2.setFont(font)
        self.lbl_mem2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2.setObjectName("lbl_mem2")
        self.gridLayout_2.addWidget(self.lbl_mem2, 3, 0, 1, 1)
        self.lineEdit_shr2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr2.setFont(font)
        self.lineEdit_shr2.setReadOnly(True)
        self.lineEdit_shr2.setObjectName("lineEdit_shr2")
        self.gridLayout_2.addWidget(self.lineEdit_shr2, 3, 2, 1, 1)
        self.lineEdit_ber2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber2.setFont(font)
        self.lineEdit_ber2.setReadOnly(True)
        self.lineEdit_ber2.setObjectName("lineEdit_ber2")
        self.gridLayout_2.addWidget(self.lineEdit_ber2, 3, 4, 1, 1)
        self.lineEdit_req2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req2.setFont(font)
        self.lineEdit_req2.setReadOnly(True)
        self.lineEdit_req2.setObjectName("lineEdit_req2")
        self.gridLayout_2.addWidget(self.lineEdit_req2, 3, 6, 1, 1)
        self.lineEdit_blt_cap2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap2.setFont(font)
        self.lineEdit_blt_cap2.setReadOnly(True)
        self.lineEdit_blt_cap2.setObjectName("lineEdit_blt_cap2")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap2, 3, 8, 1, 2)
        self.lineEdit_col2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col2.setFont(font)
        self.lineEdit_col2.setReadOnly(True)
        self.lineEdit_col2.setObjectName("lineEdit_col2")
        self.gridLayout_2.addWidget(self.lineEdit_col2, 3, 11, 1, 1)
        self.lineEdit_row2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row2.setFont(font)
        self.lineEdit_row2.setReadOnly(True)
        self.lineEdit_row2.setObjectName("lineEdit_row2")
        self.gridLayout_2.addWidget(self.lineEdit_row2, 3, 13, 1, 1)
        self.lineEdit_pitch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch2.setFont(font)
        self.lineEdit_pitch2.setReadOnly(True)
        self.lineEdit_pitch2.setObjectName("lineEdit_pitch2")
        self.gridLayout_2.addWidget(self.lineEdit_pitch2, 3, 15, 1, 1)
        self.lineEdit_gauge2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge2.setFont(font)
        self.lineEdit_gauge2.setReadOnly(True)
        self.lineEdit_gauge2.setObjectName("lineEdit_gauge2")
        self.gridLayout_2.addWidget(self.lineEdit_gauge2, 3, 17, 1, 1)
        self.lineEdit_end2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end2.setFont(font)
        self.lineEdit_end2.setReadOnly(True)
        self.lineEdit_end2.setObjectName("lineEdit_end2")
        self.gridLayout_2.addWidget(self.lineEdit_end2, 3, 19, 1, 1)
        self.lineEdit_edge2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge2.setFont(font)
        self.lineEdit_edge2.setReadOnly(True)
        self.lineEdit_edge2.setObjectName("lineEdit_edge2")
        self.gridLayout_2.addWidget(self.lineEdit_edge2, 3, 21, 1, 1)
        self.lineEdit_tens2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens2.setReadOnly(True)
        self.lineEdit_tens2.setObjectName("lineEdit_tens2")
        self.gridLayout_2.addWidget(self.lineEdit_tens2, 3, 23, 1, 1)
        self.lineEdit_block2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block2.setReadOnly(True)
        self.lineEdit_block2.setObjectName("lineEdit_block2")
        self.gridLayout_2.addWidget(self.lineEdit_block2, 3, 25, 1, 1)
        self.lbl_mem3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem3.setFont(font)
        self.lbl_mem3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem3.setObjectName("lbl_mem3")
        self.gridLayout_2.addWidget(self.lbl_mem3, 4, 0, 1, 1)
        self.lineEdit_shr3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr3.setFont(font)
        self.lineEdit_shr3.setReadOnly(True)
        self.lineEdit_shr3.setObjectName("lineEdit_shr3")
        self.gridLayout_2.addWidget(self.lineEdit_shr3, 4, 2, 1, 1)
        self.lineEdit_ber3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber3.setFont(font)
        self.lineEdit_ber3.setReadOnly(True)
        self.lineEdit_ber3.setObjectName("lineEdit_ber3")
        self.gridLayout_2.addWidget(self.lineEdit_ber3, 4, 4, 1, 1)
        self.lineEdit_req3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req3.setFont(font)
        self.lineEdit_req3.setReadOnly(True)
        self.lineEdit_req3.setObjectName("lineEdit_req3")
        self.gridLayout_2.addWidget(self.lineEdit_req3, 4, 6, 1, 1)
        self.lineEdit_blt_cap3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap3.setFont(font)
        self.lineEdit_blt_cap3.setReadOnly(True)
        self.lineEdit_blt_cap3.setObjectName("lineEdit_blt_cap3")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap3, 4, 8, 1, 2)
        self.lineEdit_col3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col3.setFont(font)
        self.lineEdit_col3.setReadOnly(True)
        self.lineEdit_col3.setObjectName("lineEdit_col3")
        self.gridLayout_2.addWidget(self.lineEdit_col3, 4, 11, 1, 1)
        self.lineEdit_row3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row3.setFont(font)
        self.lineEdit_row3.setReadOnly(True)
        self.lineEdit_row3.setObjectName("lineEdit_row3")
        self.gridLayout_2.addWidget(self.lineEdit_row3, 4, 13, 1, 1)
        self.lineEdit_pitch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch3.setFont(font)
        self.lineEdit_pitch3.setReadOnly(True)
        self.lineEdit_pitch3.setObjectName("lineEdit_pitch3")
        self.gridLayout_2.addWidget(self.lineEdit_pitch3, 4, 15, 1, 1)
        self.lineEdit_gauge3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge3.setFont(font)
        self.lineEdit_gauge3.setReadOnly(True)
        self.lineEdit_gauge3.setObjectName("lineEdit_gauge3")
        self.gridLayout_2.addWidget(self.lineEdit_gauge3, 4, 17, 1, 1)
        self.lineEdit_end3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end3.setFont(font)
        self.lineEdit_end3.setReadOnly(True)
        self.lineEdit_end3.setObjectName("lineEdit_end3")
        self.gridLayout_2.addWidget(self.lineEdit_end3, 4, 19, 1, 1)
        self.lineEdit_edge3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge3.setFont(font)
        self.lineEdit_edge3.setReadOnly(True)
        self.lineEdit_edge3.setObjectName("lineEdit_edge3")
        self.gridLayout_2.addWidget(self.lineEdit_edge3, 4, 21, 1, 1)
        self.lineEdit_tens3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens3.setReadOnly(True)
        self.lineEdit_tens3.setObjectName("lineEdit_tens3")
        self.gridLayout_2.addWidget(self.lineEdit_tens3, 4, 23, 1, 1)
        self.lineEdit_block3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block3.setReadOnly(True)
        self.lineEdit_block3.setObjectName("lineEdit_block3")
        self.gridLayout_2.addWidget(self.lineEdit_block3, 4, 25, 1, 1)
        self.lbl_mem4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem4.setFont(font)
        self.lbl_mem4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem4.setObjectName("lbl_mem4")
        self.gridLayout_2.addWidget(self.lbl_mem4, 5, 0, 1, 1)
        self.lineEdit_shr4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr4.setFont(font)
        self.lineEdit_shr4.setReadOnly(True)
        self.lineEdit_shr4.setObjectName("lineEdit_shr4")
        self.gridLayout_2.addWidget(self.lineEdit_shr4, 5, 2, 1, 1)
        self.lineEdit_ber4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber4.setFont(font)
        self.lineEdit_ber4.setReadOnly(True)
        self.lineEdit_ber4.setObjectName("lineEdit_ber4")
        self.gridLayout_2.addWidget(self.lineEdit_ber4, 5, 4, 1, 1)
        self.lineEdit_req4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req4.setFont(font)
        self.lineEdit_req4.setReadOnly(True)
        self.lineEdit_req4.setObjectName("lineEdit_req4")
        self.gridLayout_2.addWidget(self.lineEdit_req4, 5, 6, 1, 1)
        self.lineEdit_blt_cap4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap4.setFont(font)
        self.lineEdit_blt_cap4.setReadOnly(True)
        self.lineEdit_blt_cap4.setObjectName("lineEdit_blt_cap4")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap4, 5, 8, 1, 2)
        self.lineEdit_col4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col4.setFont(font)
        self.lineEdit_col4.setReadOnly(True)
        self.lineEdit_col4.setObjectName("lineEdit_col4")
        self.gridLayout_2.addWidget(self.lineEdit_col4, 5, 11, 1, 1)
        self.lineEdit_row4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row4.setFont(font)
        self.lineEdit_row4.setReadOnly(True)
        self.lineEdit_row4.setObjectName("lineEdit_row4")
        self.gridLayout_2.addWidget(self.lineEdit_row4, 5, 13, 1, 1)
        self.lineEdit_pitch4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch4.setFont(font)
        self.lineEdit_pitch4.setReadOnly(True)
        self.lineEdit_pitch4.setObjectName("lineEdit_pitch4")
        self.gridLayout_2.addWidget(self.lineEdit_pitch4, 5, 15, 1, 1)
        self.lineEdit_gauge4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge4.setFont(font)
        self.lineEdit_gauge4.setReadOnly(True)
        self.lineEdit_gauge4.setObjectName("lineEdit_gauge4")
        self.gridLayout_2.addWidget(self.lineEdit_gauge4, 5, 17, 1, 1)
        self.lineEdit_end4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end4.setFont(font)
        self.lineEdit_end4.setReadOnly(True)
        self.lineEdit_end4.setObjectName("lineEdit_end4")
        self.gridLayout_2.addWidget(self.lineEdit_end4, 5, 19, 1, 1)
        self.lineEdit_edge4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge4.setFont(font)
        self.lineEdit_edge4.setReadOnly(True)
        self.lineEdit_edge4.setObjectName("lineEdit_edge4")
        self.gridLayout_2.addWidget(self.lineEdit_edge4, 5, 21, 1, 1)
        self.lineEdit_tens4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens4.setReadOnly(True)
        self.lineEdit_tens4.setObjectName("lineEdit_tens4")
        self.gridLayout_2.addWidget(self.lineEdit_tens4, 5, 23, 1, 1)
        self.lineEdit_block4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block4.setReadOnly(True)
        self.lineEdit_block4.setObjectName("lineEdit_block4")
        self.gridLayout_2.addWidget(self.lineEdit_block4, 5, 25, 1, 1)
        self.lbl_mem5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem5.setFont(font)
        self.lbl_mem5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem5.setObjectName("lbl_mem5")
        self.gridLayout_2.addWidget(self.lbl_mem5, 6, 0, 1, 1)
        self.lineEdit_shr5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr5.setFont(font)
        self.lineEdit_shr5.setReadOnly(True)
        self.lineEdit_shr5.setObjectName("lineEdit_shr5")
        self.gridLayout_2.addWidget(self.lineEdit_shr5, 6, 2, 1, 1)
        self.lineEdit_ber5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber5.setFont(font)
        self.lineEdit_ber5.setReadOnly(True)
        self.lineEdit_ber5.setObjectName("lineEdit_ber5")
        self.gridLayout_2.addWidget(self.lineEdit_ber5, 6, 4, 1, 1)
        self.lineEdit_req5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req5.setFont(font)
        self.lineEdit_req5.setReadOnly(True)
        self.lineEdit_req5.setObjectName("lineEdit_req5")
        self.gridLayout_2.addWidget(self.lineEdit_req5, 6, 6, 1, 1)
        self.lineEdit_blt_cap5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap5.setFont(font)
        self.lineEdit_blt_cap5.setReadOnly(True)
        self.lineEdit_blt_cap5.setObjectName("lineEdit_blt_cap5")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap5, 6, 8, 1, 2)
        self.lineEdit_col5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col5.setFont(font)
        self.lineEdit_col5.setReadOnly(True)
        self.lineEdit_col5.setObjectName("lineEdit_col5")
        self.gridLayout_2.addWidget(self.lineEdit_col5, 6, 11, 1, 1)
        self.lineEdit_row5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row5.setFont(font)
        self.lineEdit_row5.setReadOnly(True)
        self.lineEdit_row5.setObjectName("lineEdit_row5")
        self.gridLayout_2.addWidget(self.lineEdit_row5, 6, 13, 1, 1)
        self.lineEdit_pitch5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch5.setFont(font)
        self.lineEdit_pitch5.setReadOnly(True)
        self.lineEdit_pitch5.setObjectName("lineEdit_pitch5")
        self.gridLayout_2.addWidget(self.lineEdit_pitch5, 6, 15, 1, 1)
        self.lineEdit_gauge5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge5.setFont(font)
        self.lineEdit_gauge5.setReadOnly(True)
        self.lineEdit_gauge5.setObjectName("lineEdit_gauge5")
        self.gridLayout_2.addWidget(self.lineEdit_gauge5, 6, 17, 1, 1)
        self.lineEdit_end5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end5.setFont(font)
        self.lineEdit_end5.setReadOnly(True)
        self.lineEdit_end5.setObjectName("lineEdit_end5")
        self.gridLayout_2.addWidget(self.lineEdit_end5, 6, 19, 1, 1)
        self.lineEdit_edge5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge5.setFont(font)
        self.lineEdit_edge5.setReadOnly(True)
        self.lineEdit_edge5.setObjectName("lineEdit_edge5")
        self.gridLayout_2.addWidget(self.lineEdit_edge5, 6, 21, 1, 1)
        self.lineEdit_tens5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens5.setReadOnly(True)
        self.lineEdit_tens5.setObjectName("lineEdit_tens5")
        self.gridLayout_2.addWidget(self.lineEdit_tens5, 6, 23, 1, 1)
        self.lineEdit_block5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block5.setReadOnly(True)
        self.lineEdit_block5.setObjectName("lineEdit_block5")
        self.gridLayout_2.addWidget(self.lineEdit_block5, 6, 25, 1, 1)
        self.lbl_mem6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem6.setFont(font)
        self.lbl_mem6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem6.setObjectName("lbl_mem6")
        self.gridLayout_2.addWidget(self.lbl_mem6, 7, 0, 1, 1)
        self.lineEdit_shr6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr6.setFont(font)
        self.lineEdit_shr6.setReadOnly(True)
        self.lineEdit_shr6.setObjectName("lineEdit_shr6")
        self.gridLayout_2.addWidget(self.lineEdit_shr6, 7, 2, 1, 1)
        self.lineEdit_ber6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber6.setFont(font)
        self.lineEdit_ber6.setReadOnly(True)
        self.lineEdit_ber6.setObjectName("lineEdit_ber6")
        self.gridLayout_2.addWidget(self.lineEdit_ber6, 7, 4, 1, 1)
        self.lineEdit_req6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req6.setFont(font)
        self.lineEdit_req6.setReadOnly(True)
        self.lineEdit_req6.setObjectName("lineEdit_req6")
        self.gridLayout_2.addWidget(self.lineEdit_req6, 7, 6, 1, 1)
        self.lineEdit_blt_cap6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap6.setFont(font)
        self.lineEdit_blt_cap6.setReadOnly(True)
        self.lineEdit_blt_cap6.setObjectName("lineEdit_blt_cap6")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap6, 7, 8, 1, 2)
        self.lineEdit_col6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col6.setFont(font)
        self.lineEdit_col6.setReadOnly(True)
        self.lineEdit_col6.setObjectName("lineEdit_col6")
        self.gridLayout_2.addWidget(self.lineEdit_col6, 7, 11, 1, 1)
        self.lineEdit_row6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row6.setFont(font)
        self.lineEdit_row6.setReadOnly(True)
        self.lineEdit_row6.setObjectName("lineEdit_row6")
        self.gridLayout_2.addWidget(self.lineEdit_row6, 7, 13, 1, 1)
        self.lineEdit_pitch6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch6.setFont(font)
        self.lineEdit_pitch6.setReadOnly(True)
        self.lineEdit_pitch6.setObjectName("lineEdit_pitch6")
        self.gridLayout_2.addWidget(self.lineEdit_pitch6, 7, 15, 1, 1)
        self.lineEdit_gauge6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge6.setFont(font)
        self.lineEdit_gauge6.setReadOnly(True)
        self.lineEdit_gauge6.setObjectName("lineEdit_gauge6")
        self.gridLayout_2.addWidget(self.lineEdit_gauge6, 7, 17, 1, 1)
        self.lineEdit_end6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end6.setFont(font)
        self.lineEdit_end6.setReadOnly(True)
        self.lineEdit_end6.setObjectName("lineEdit_end6")
        self.gridLayout_2.addWidget(self.lineEdit_end6, 7, 19, 1, 1)
        self.lineEdit_edge6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge6.setFont(font)
        self.lineEdit_edge6.setReadOnly(True)
        self.lineEdit_edge6.setObjectName("lineEdit_edge6")
        self.gridLayout_2.addWidget(self.lineEdit_edge6, 7, 21, 1, 1)
        self.lineEdit_tens6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens6.setReadOnly(True)
        self.lineEdit_tens6.setObjectName("lineEdit_tens6")
        self.gridLayout_2.addWidget(self.lineEdit_tens6, 7, 23, 1, 1)
        self.lineEdit_block6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block6.setReadOnly(True)
        self.lineEdit_block6.setObjectName("lineEdit_block6")
        self.gridLayout_2.addWidget(self.lineEdit_block6, 7, 25, 1, 1)
        self.lbl_mem7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem7.setFont(font)
        self.lbl_mem7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem7.setObjectName("lbl_mem7")
        self.gridLayout_2.addWidget(self.lbl_mem7, 8, 0, 1, 1)
        self.lineEdit_shr7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr7.setFont(font)
        self.lineEdit_shr7.setReadOnly(True)
        self.lineEdit_shr7.setObjectName("lineEdit_shr7")
        self.gridLayout_2.addWidget(self.lineEdit_shr7, 8, 2, 1, 1)
        self.lineEdit_ber7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber7.setFont(font)
        self.lineEdit_ber7.setReadOnly(True)
        self.lineEdit_ber7.setObjectName("lineEdit_ber7")
        self.gridLayout_2.addWidget(self.lineEdit_ber7, 8, 4, 1, 1)
        self.lineEdit_req7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req7.setFont(font)
        self.lineEdit_req7.setReadOnly(True)
        self.lineEdit_req7.setObjectName("lineEdit_req7")
        self.gridLayout_2.addWidget(self.lineEdit_req7, 8, 6, 1, 1)
        self.lineEdit_blt_cap7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap7.setFont(font)
        self.lineEdit_blt_cap7.setReadOnly(True)
        self.lineEdit_blt_cap7.setObjectName("lineEdit_blt_cap7")
        self.gridLayout_2.addWidget(self.lineEdit_blt_cap7, 8, 8, 1, 2)
        self.lineEdit_col7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col7.setFont(font)
        self.lineEdit_col7.setReadOnly(True)
        self.lineEdit_col7.setObjectName("lineEdit_col7")
        self.gridLayout_2.addWidget(self.lineEdit_col7, 8, 11, 1, 1)
        self.lineEdit_row7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row7.setFont(font)
        self.lineEdit_row7.setReadOnly(True)
        self.lineEdit_row7.setObjectName("lineEdit_row7")
        self.gridLayout_2.addWidget(self.lineEdit_row7, 8, 13, 1, 1)
        self.lineEdit_pitch7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch7.setFont(font)
        self.lineEdit_pitch7.setReadOnly(True)
        self.lineEdit_pitch7.setObjectName("lineEdit_pitch7")
        self.gridLayout_2.addWidget(self.lineEdit_pitch7, 8, 15, 1, 1)
        self.lineEdit_gauge7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_gauge7.setFont(font)
        self.lineEdit_gauge7.setReadOnly(True)
        self.lineEdit_gauge7.setObjectName("lineEdit_gauge7")
        self.gridLayout_2.addWidget(self.lineEdit_gauge7, 8, 17, 1, 1)
        self.lineEdit_end7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_end7.setFont(font)
        self.lineEdit_end7.setReadOnly(True)
        self.lineEdit_end7.setObjectName("lineEdit_end7")
        self.gridLayout_2.addWidget(self.lineEdit_end7, 8, 19, 1, 1)
        self.lineEdit_edge7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_edge7.setFont(font)
        self.lineEdit_edge7.setReadOnly(True)
        self.lineEdit_edge7.setObjectName("lineEdit_edge7")
        self.gridLayout_2.addWidget(self.lineEdit_edge7, 8, 21, 1, 1)
        self.lineEdit_tens7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tens7.setReadOnly(True)
        self.lineEdit_tens7.setObjectName("lineEdit_tens7")
        self.gridLayout_2.addWidget(self.lineEdit_tens7, 8, 23, 1, 1)
        self.lineEdit_block7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_block7.setReadOnly(True)
        self.lineEdit_block7.setObjectName("lineEdit_block7")
        self.gridLayout_2.addWidget(self.lineEdit_block7, 8, 25, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Member output"))
        self.label.setText(_translate("Dialog", "Member"))
        self.label_2.setText(_translate("Dialog", "Shear\n"
"capacity (kN)"))
        self.label_3.setText(_translate("Dialog", "Bearing\n"
"capacity (kN)"))
        self.label_11.setText(_translate("Dialog", "No. of bolts\n"
"required"))
        self.label_4.setText(_translate("Dialog", "Bolt group\n"
"capacity (kN)"))
        self.label_9.setText(_translate("Dialog", "No. of\n"
"columns"))
        self.label_10.setText(_translate("Dialog", "No. of\n"
"rows"))
        self.label_5.setText(_translate("Dialog", "Pitch (mm)"))
        self.label_6.setText(_translate("Dialog", "Gauge (mm)"))
        self.label_7.setText(_translate("Dialog", "End\n"
"distance (mm)"))
        self.label_8.setText(_translate("Dialog", "Edge\n"
"distance (mm)"))
        self.label_12.setText(_translate("Dialog", "Tension\n"
"capacity (kN)"))
        self.label_13.setText(_translate("Dialog", "Block shear\n"
"capacity (kN)"))
        self.lbl_mem.setText(_translate("Dialog", "1"))
        self.lbl_mem2.setText(_translate("Dialog", "2"))
        self.lbl_mem3.setText(_translate("Dialog", "3"))
        self.lbl_mem4.setText(_translate("Dialog", "4"))
        self.lbl_mem5.setText(_translate("Dialog", "5"))
        self.lbl_mem6.setText(_translate("Dialog", "6"))
        self.lbl_mem7.setText(_translate("Dialog", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_BoltOutput()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

