# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_output.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BoltOutput(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1164, 271)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 8, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 8, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 6, 8, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 7, 1, 1)
        self.line_10 = QtWidgets.QFrame(Dialog)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 0, 8, 8, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 10, 1, 1)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 11, 8, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 12, 1, 1)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 0, 13, 8, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 14, 1, 1)
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 15, 8, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 16, 1, 1)
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 0, 17, 8, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 18, 1, 1)
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 19, 8, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 20, 1, 1)
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 0, 21, 8, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 22, 1, 1)
        self.lineEdit_mem = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem.setFont(font)
        self.lineEdit_mem.setReadOnly(True)
        self.lineEdit_mem.setObjectName("lineEdit_mem")
        self.gridLayout.addWidget(self.lineEdit_mem, 1, 0, 1, 1)
        self.lineEdit_shr = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr.setFont(font)
        self.lineEdit_shr.setObjectName("lineEdit_shr")
        self.gridLayout.addWidget(self.lineEdit_shr, 1, 3, 1, 1)
        self.lineEdit_ber = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber.setFont(font)
        self.lineEdit_ber.setObjectName("lineEdit_ber")
        self.gridLayout.addWidget(self.lineEdit_ber, 1, 5, 1, 1)
        self.lineEdit_req = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req.setFont(font)
        self.lineEdit_req.setObjectName("lineEdit_req")
        self.gridLayout.addWidget(self.lineEdit_req, 1, 7, 1, 1)
        self.lineEdit_blt_cap = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap.setFont(font)
        self.lineEdit_blt_cap.setObjectName("lineEdit_blt_cap")
        self.gridLayout.addWidget(self.lineEdit_blt_cap, 1, 9, 1, 2)
        self.lineEdit_col = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col.setFont(font)
        self.lineEdit_col.setObjectName("lineEdit_col")
        self.gridLayout.addWidget(self.lineEdit_col, 1, 12, 1, 1)
        self.lineEdit_row = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.gridLayout.addWidget(self.lineEdit_row, 1, 14, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_45.setFont(font)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 1, 16, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_52.setFont(font)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 1, 18, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_59.setFont(font)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout.addWidget(self.lineEdit_59, 1, 20, 1, 1)
        self.lineEdit_66 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_66.setFont(font)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout.addWidget(self.lineEdit_66, 1, 22, 1, 1)
        self.lineEdit_mem2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem2.setFont(font)
        self.lineEdit_mem2.setReadOnly(True)
        self.lineEdit_mem2.setObjectName("lineEdit_mem2")
        self.gridLayout.addWidget(self.lineEdit_mem2, 2, 0, 1, 1)
        self.lineEdit_shr2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr2.setFont(font)
        self.lineEdit_shr2.setObjectName("lineEdit_shr2")
        self.gridLayout.addWidget(self.lineEdit_shr2, 2, 3, 1, 1)
        self.lineEdit_ber2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber2.setFont(font)
        self.lineEdit_ber2.setObjectName("lineEdit_ber2")
        self.gridLayout.addWidget(self.lineEdit_ber2, 2, 5, 1, 1)
        self.lineEdit_req2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req2.setFont(font)
        self.lineEdit_req2.setObjectName("lineEdit_req2")
        self.gridLayout.addWidget(self.lineEdit_req2, 2, 7, 1, 1)
        self.lineEdit_blt_cap2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap2.setFont(font)
        self.lineEdit_blt_cap2.setObjectName("lineEdit_blt_cap2")
        self.gridLayout.addWidget(self.lineEdit_blt_cap2, 2, 9, 1, 2)
        self.lineEdit_col2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col2.setFont(font)
        self.lineEdit_col2.setObjectName("lineEdit_col2")
        self.gridLayout.addWidget(self.lineEdit_col2, 2, 12, 1, 1)
        self.lineEdit_row2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row2.setFont(font)
        self.lineEdit_row2.setObjectName("lineEdit_row2")
        self.gridLayout.addWidget(self.lineEdit_row2, 2, 14, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_47.setFont(font)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 2, 16, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_54.setFont(font)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 2, 18, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_61.setFont(font)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout.addWidget(self.lineEdit_61, 2, 20, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_68.setFont(font)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout.addWidget(self.lineEdit_68, 2, 22, 1, 1)
        self.lineEdit_mem3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem3.setFont(font)
        self.lineEdit_mem3.setReadOnly(True)
        self.lineEdit_mem3.setObjectName("lineEdit_mem3")
        self.gridLayout.addWidget(self.lineEdit_mem3, 3, 0, 1, 1)
        self.lineEdit_shr3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr3.setFont(font)
        self.lineEdit_shr3.setObjectName("lineEdit_shr3")
        self.gridLayout.addWidget(self.lineEdit_shr3, 3, 3, 1, 1)
        self.lineEdit_ber3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber3.setFont(font)
        self.lineEdit_ber3.setObjectName("lineEdit_ber3")
        self.gridLayout.addWidget(self.lineEdit_ber3, 3, 5, 1, 1)
        self.lineEdit_req3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req3.setFont(font)
        self.lineEdit_req3.setObjectName("lineEdit_req3")
        self.gridLayout.addWidget(self.lineEdit_req3, 3, 7, 1, 1)
        self.lineEdit_blt_cap3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap3.setFont(font)
        self.lineEdit_blt_cap3.setObjectName("lineEdit_blt_cap3")
        self.gridLayout.addWidget(self.lineEdit_blt_cap3, 3, 9, 1, 2)
        self.lineEdit_col3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col3.setFont(font)
        self.lineEdit_col3.setObjectName("lineEdit_col3")
        self.gridLayout.addWidget(self.lineEdit_col3, 3, 12, 1, 1)
        self.lineEdit_row3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row3.setFont(font)
        self.lineEdit_row3.setObjectName("lineEdit_row3")
        self.gridLayout.addWidget(self.lineEdit_row3, 3, 14, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 3, 16, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_50.setFont(font)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 3, 18, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_57.setFont(font)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout.addWidget(self.lineEdit_57, 3, 20, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_64.setFont(font)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout.addWidget(self.lineEdit_64, 3, 22, 1, 1)
        self.lineEdit_mem4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem4.setFont(font)
        self.lineEdit_mem4.setReadOnly(True)
        self.lineEdit_mem4.setObjectName("lineEdit_mem4")
        self.gridLayout.addWidget(self.lineEdit_mem4, 4, 0, 1, 1)
        self.lineEdit_shr4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr4.setFont(font)
        self.lineEdit_shr4.setObjectName("lineEdit_shr4")
        self.gridLayout.addWidget(self.lineEdit_shr4, 4, 3, 1, 1)
        self.lineEdit_ber4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber4.setFont(font)
        self.lineEdit_ber4.setObjectName("lineEdit_ber4")
        self.gridLayout.addWidget(self.lineEdit_ber4, 4, 5, 1, 1)
        self.lineEdit_req4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req4.setFont(font)
        self.lineEdit_req4.setObjectName("lineEdit_req4")
        self.gridLayout.addWidget(self.lineEdit_req4, 4, 7, 1, 1)
        self.lineEdit_blt_cap4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap4.setFont(font)
        self.lineEdit_blt_cap4.setObjectName("lineEdit_blt_cap4")
        self.gridLayout.addWidget(self.lineEdit_blt_cap4, 4, 9, 1, 2)
        self.lineEdit_col4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col4.setFont(font)
        self.lineEdit_col4.setObjectName("lineEdit_col4")
        self.gridLayout.addWidget(self.lineEdit_col4, 4, 12, 1, 1)
        self.lineEdit_row4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row4.setFont(font)
        self.lineEdit_row4.setObjectName("lineEdit_row4")
        self.gridLayout.addWidget(self.lineEdit_row4, 4, 14, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_46.setFont(font)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 4, 16, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_53.setFont(font)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 4, 18, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_60.setFont(font)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout.addWidget(self.lineEdit_60, 4, 20, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_67.setFont(font)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout.addWidget(self.lineEdit_67, 4, 22, 1, 1)
        self.lineEdit_mem5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem5.setFont(font)
        self.lineEdit_mem5.setReadOnly(True)
        self.lineEdit_mem5.setObjectName("lineEdit_mem5")
        self.gridLayout.addWidget(self.lineEdit_mem5, 5, 0, 1, 1)
        self.lineEdit_shr5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr5.setFont(font)
        self.lineEdit_shr5.setObjectName("lineEdit_shr5")
        self.gridLayout.addWidget(self.lineEdit_shr5, 5, 3, 1, 1)
        self.lineEdit_ber5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber5.setFont(font)
        self.lineEdit_ber5.setObjectName("lineEdit_ber5")
        self.gridLayout.addWidget(self.lineEdit_ber5, 5, 5, 1, 1)
        self.lineEdit_req5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req5.setFont(font)
        self.lineEdit_req5.setObjectName("lineEdit_req5")
        self.gridLayout.addWidget(self.lineEdit_req5, 5, 7, 1, 1)
        self.lineEdit_blt_cap5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap5.setFont(font)
        self.lineEdit_blt_cap5.setObjectName("lineEdit_blt_cap5")
        self.gridLayout.addWidget(self.lineEdit_blt_cap5, 5, 9, 1, 2)
        self.lineEdit_col5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col5.setFont(font)
        self.lineEdit_col5.setObjectName("lineEdit_col5")
        self.gridLayout.addWidget(self.lineEdit_col5, 5, 12, 1, 1)
        self.lineEdit_row5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row5.setFont(font)
        self.lineEdit_row5.setObjectName("lineEdit_row5")
        self.gridLayout.addWidget(self.lineEdit_row5, 5, 14, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_49.setFont(font)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout.addWidget(self.lineEdit_49, 5, 16, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_56.setFont(font)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 5, 18, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_63.setFont(font)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout.addWidget(self.lineEdit_63, 5, 20, 1, 1)
        self.lineEdit_70 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_70.setFont(font)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout.addWidget(self.lineEdit_70, 5, 22, 1, 1)
        self.lineEdit_mem6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem6.setFont(font)
        self.lineEdit_mem6.setReadOnly(True)
        self.lineEdit_mem6.setObjectName("lineEdit_mem6")
        self.gridLayout.addWidget(self.lineEdit_mem6, 6, 0, 1, 1)
        self.lineEdit_shr6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr6.setFont(font)
        self.lineEdit_shr6.setObjectName("lineEdit_shr6")
        self.gridLayout.addWidget(self.lineEdit_shr6, 6, 3, 1, 1)
        self.lineEdit_ber6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber6.setFont(font)
        self.lineEdit_ber6.setObjectName("lineEdit_ber6")
        self.gridLayout.addWidget(self.lineEdit_ber6, 6, 5, 1, 1)
        self.lineEdit_req6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req6.setFont(font)
        self.lineEdit_req6.setObjectName("lineEdit_req6")
        self.gridLayout.addWidget(self.lineEdit_req6, 6, 7, 1, 1)
        self.lineEdit_blt_cap6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap6.setFont(font)
        self.lineEdit_blt_cap6.setObjectName("lineEdit_blt_cap6")
        self.gridLayout.addWidget(self.lineEdit_blt_cap6, 6, 9, 1, 2)
        self.lineEdit_col6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col6.setFont(font)
        self.lineEdit_col6.setObjectName("lineEdit_col6")
        self.gridLayout.addWidget(self.lineEdit_col6, 6, 12, 1, 1)
        self.lineEdit_row6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row6.setFont(font)
        self.lineEdit_row6.setObjectName("lineEdit_row6")
        self.gridLayout.addWidget(self.lineEdit_row6, 6, 14, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout.addWidget(self.lineEdit_48, 6, 16, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_55.setFont(font)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 6, 18, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_62.setFont(font)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout.addWidget(self.lineEdit_62, 6, 20, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_69.setFont(font)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout.addWidget(self.lineEdit_69, 6, 22, 1, 1)
        self.lineEdit_mem7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_mem7.setFont(font)
        self.lineEdit_mem7.setReadOnly(True)
        self.lineEdit_mem7.setObjectName("lineEdit_mem7")
        self.gridLayout.addWidget(self.lineEdit_mem7, 7, 0, 1, 1)
        self.lineEdit_shr7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_shr7.setFont(font)
        self.lineEdit_shr7.setObjectName("lineEdit_shr7")
        self.gridLayout.addWidget(self.lineEdit_shr7, 7, 3, 1, 1)
        self.lineEdit_ber7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_ber7.setFont(font)
        self.lineEdit_ber7.setObjectName("lineEdit_ber7")
        self.gridLayout.addWidget(self.lineEdit_ber7, 7, 5, 1, 1)
        self.lineEdit_req7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_req7.setFont(font)
        self.lineEdit_req7.setObjectName("lineEdit_req7")
        self.gridLayout.addWidget(self.lineEdit_req7, 7, 7, 1, 1)
        self.lineEdit_blt_cap7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_blt_cap7.setFont(font)
        self.lineEdit_blt_cap7.setObjectName("lineEdit_blt_cap7")
        self.gridLayout.addWidget(self.lineEdit_blt_cap7, 7, 9, 1, 2)
        self.lineEdit_col7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_col7.setFont(font)
        self.lineEdit_col7.setObjectName("lineEdit_col7")
        self.gridLayout.addWidget(self.lineEdit_col7, 7, 12, 1, 1)
        self.lineEdit_row7 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_row7.setFont(font)
        self.lineEdit_row7.setObjectName("lineEdit_row7")
        self.gridLayout.addWidget(self.lineEdit_row7, 7, 14, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 7, 16, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_51.setFont(font)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 7, 18, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout.addWidget(self.lineEdit_58, 7, 20, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_65.setFont(font)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout.addWidget(self.lineEdit_65, 7, 22, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Members"))
        self.label_2.setText(_translate("Dialog", "Shear\n"
"capacity (kN)"))
        self.label_3.setText(_translate("Dialog", "Bearing\n"
"capacity (kN)"))
        self.label_11.setText(_translate("Dialog", "No. of bolts\n"
"required"))
        self.label_4.setText(_translate("Dialog", "Bolt group\n"
"capacity (kN)"))
        self.label_9.setText(_translate("Dialog", "No. of\n"
"Columns"))
        self.label_10.setText(_translate("Dialog", "No. of\n"
"Rows"))
        self.label_5.setText(_translate("Dialog", "Pitch (mm)"))
        self.label_6.setText(_translate("Dialog", "Gauge (mm)"))
        self.label_7.setText(_translate("Dialog", "End\n"
"distance (mm)"))
        self.label_8.setText(_translate("Dialog", "Edge\n"
"distance (mm)"))
        self.lineEdit_mem.setPlaceholderText(_translate("Dialog", "1"))
        self.lineEdit_mem2.setPlaceholderText(_translate("Dialog", "2"))
        self.lineEdit_mem3.setPlaceholderText(_translate("Dialog", "3"))
        self.lineEdit_mem4.setPlaceholderText(_translate("Dialog", "4"))
        self.lineEdit_mem5.setPlaceholderText(_translate("Dialog", "5"))
        self.lineEdit_mem6.setPlaceholderText(_translate("Dialog", "6"))
        self.lineEdit_mem7.setPlaceholderText(_translate("Dialog", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_BoltOutput()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

