# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_selection.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Selection(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 402)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_3.addWidget(self.btn_save)
        self.btn_reset = QtWidgets.QPushButton(Dialog)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_3.addWidget(self.btn_reset)
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 15, 3, 1, 3)
        self.lineEdit_loads_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_2.setObjectName("lineEdit_loads_2")
        self.gridLayout.addWidget(self.lineEdit_loads_2, 4, 10, 1, 1)
        self.lineEdit_no_of_member_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_3.setReadOnly(True)
        self.lineEdit_no_of_member_3.setObjectName("lineEdit_no_of_member_3")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_3, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 5, 1, 2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 9, 1, 2)
        self.lineEdit_no_of_member_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_4.setReadOnly(True)
        self.lineEdit_no_of_member_4.setObjectName("lineEdit_no_of_member_4")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_4, 8, 0, 1, 1)
        self.lineEdit_no_of_member_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_5.setReadOnly(True)
        self.lineEdit_no_of_member_5.setObjectName("lineEdit_no_of_member_5")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_5, 10, 0, 1, 1)
        self.lineEdit_angle_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_5.setObjectName("lineEdit_angle_5")
        self.gridLayout.addWidget(self.lineEdit_angle_5, 10, 2, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBx_selection_2 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_2.setFont(font)
        self.comboBx_selection_2.setObjectName("comboBx_selection_2")
        self.comboBx_selection_2.addItem("")
        self.comboBx_selection_2.addItem("")
        self.comboBx_selection_2.addItem("")
        self.comboBx_selection_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBx_selection_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lbl_sectionSelection_2 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_2.setText("")
        self.lbl_sectionSelection_2.setObjectName("lbl_sectionSelection_2")
        self.horizontalLayout.addWidget(self.lbl_sectionSelection_2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 5, 2, 1)
        self.lineEdit_no_of_member_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_2.setReadOnly(True)
        self.lineEdit_no_of_member_2.setObjectName("lineEdit_no_of_member_2")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_2, 4, 0, 1, 1)
        self.lineEdit_loads_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_5.setObjectName("lineEdit_loads_5")
        self.gridLayout.addWidget(self.lineEdit_loads_5, 10, 10, 1, 1)
        self.lineEdit_no_of_member = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member.setReadOnly(True)
        self.lineEdit_no_of_member.setObjectName("lineEdit_no_of_member")
        self.gridLayout.addWidget(self.lineEdit_no_of_member, 2, 0, 1, 1)
        self.lineEdit_angle_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_4.setObjectName("lineEdit_angle_4")
        self.gridLayout.addWidget(self.lineEdit_angle_4, 8, 2, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBx_selection_6 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_6.setFont(font)
        self.comboBx_selection_6.setObjectName("comboBx_selection_6")
        self.comboBx_selection_6.addItem("")
        self.comboBx_selection_6.addItem("")
        self.comboBx_selection_6.addItem("")
        self.comboBx_selection_6.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBx_selection_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.lbl_sectionSelection_6 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_6.setText("")
        self.lbl_sectionSelection_6.setObjectName("lbl_sectionSelection_6")
        self.horizontalLayout_7.addWidget(self.lbl_sectionSelection_6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 11, 5, 2, 1)
        self.lineEdit_loads_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_4.setObjectName("lineEdit_loads_4")
        self.gridLayout.addWidget(self.lineEdit_loads_4, 8, 10, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBx_selection_5 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_5.setFont(font)
        self.comboBx_selection_5.setObjectName("comboBx_selection_5")
        self.comboBx_selection_5.addItem("")
        self.comboBx_selection_5.addItem("")
        self.comboBx_selection_5.addItem("")
        self.comboBx_selection_5.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBx_selection_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.lbl_sectionSelection_5 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_5.setText("")
        self.lbl_sectionSelection_5.setObjectName("lbl_sectionSelection_5")
        self.horizontalLayout_6.addWidget(self.lbl_sectionSelection_5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 9, 5, 2, 1)
        self.lineEdit_no_of_member_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_6.setReadOnly(True)
        self.lineEdit_no_of_member_6.setObjectName("lineEdit_no_of_member_6")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_6, 12, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBx_selection_3 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_3.setFont(font)
        self.comboBx_selection_3.setObjectName("comboBx_selection_3")
        self.comboBx_selection_3.addItem("")
        self.comboBx_selection_3.addItem("")
        self.comboBx_selection_3.addItem("")
        self.comboBx_selection_3.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBx_selection_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.lbl_sectionSelection_3 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_3.setText("")
        self.lbl_sectionSelection_3.setObjectName("lbl_sectionSelection_3")
        self.horizontalLayout_4.addWidget(self.lbl_sectionSelection_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 5, 2, 1)
        self.lineEdit_angle_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_3.setObjectName("lineEdit_angle_3")
        self.gridLayout.addWidget(self.lineEdit_angle_3, 6, 2, 1, 2)
        self.lineEdit_loads = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads.setObjectName("lineEdit_loads")
        self.gridLayout.addWidget(self.lineEdit_loads, 2, 10, 1, 1)
        self.lineEdit_loads_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_3.setObjectName("lineEdit_loads_3")
        self.gridLayout.addWidget(self.lineEdit_loads_3, 6, 10, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 8, 15, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 15, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBx_selection = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection.setFont(font)
        self.comboBx_selection.setObjectName("comboBx_selection")
        self.comboBx_selection.addItem("")
        self.comboBx_selection.addItem("")
        self.comboBx_selection.addItem("")
        self.comboBx_selection.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBx_selection)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.lbl_sectionSelection = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection.setText("")
        self.lbl_sectionSelection.setObjectName("lbl_sectionSelection")
        self.horizontalLayout_2.addWidget(self.lbl_sectionSelection)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 5, 2, 1)
        self.lineEdit_angle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.gridLayout.addWidget(self.lineEdit_angle, 2, 2, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBx_selection_4 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_4.setFont(font)
        self.comboBx_selection_4.setObjectName("comboBx_selection_4")
        self.comboBx_selection_4.addItem("")
        self.comboBx_selection_4.addItem("")
        self.comboBx_selection_4.addItem("")
        self.comboBx_selection_4.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBx_selection_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.lbl_sectionSelection_4 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_4.setText("")
        self.lbl_sectionSelection_4.setObjectName("lbl_sectionSelection_4")
        self.horizontalLayout_5.addWidget(self.lbl_sectionSelection_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 5, 2, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/images/inclination.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 15, 1)
        self.lineEdit_angle_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_2.setObjectName("lineEdit_angle_2")
        self.gridLayout.addWidget(self.lineEdit_angle_2, 4, 2, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 15, 2, 1, 1)
        self.lineEdit_angle_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_6.setObjectName("lineEdit_angle_6")
        self.gridLayout.addWidget(self.lineEdit_angle_6, 12, 2, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 15, 10, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBx_selection_7 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBx_selection_7.setFont(font)
        self.comboBx_selection_7.setObjectName("comboBx_selection_7")
        self.comboBx_selection_7.addItem("")
        self.comboBx_selection_7.addItem("")
        self.comboBx_selection_7.addItem("")
        self.comboBx_selection_7.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBx_selection_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.lbl_sectionSelection_7 = QtWidgets.QLabel(Dialog)
        self.lbl_sectionSelection_7.setText("")
        self.lbl_sectionSelection_7.setObjectName("lbl_sectionSelection_7")
        self.horizontalLayout_8.addWidget(self.lbl_sectionSelection_7)
        self.gridLayout.addLayout(self.horizontalLayout_8, 13, 5, 2, 1)
        self.lineEdit_no_of_member_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_no_of_member_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_no_of_member_7.setReadOnly(True)
        self.lineEdit_no_of_member_7.setObjectName("lineEdit_no_of_member_7")
        self.gridLayout.addWidget(self.lineEdit_no_of_member_7, 14, 0, 1, 1)
        self.lineEdit_angle_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_angle_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.lineEdit_angle_7.setObjectName("lineEdit_angle_7")
        self.gridLayout.addWidget(self.lineEdit_angle_7, 14, 2, 1, 2)
        self.lineEdit_loads_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_6.setObjectName("lineEdit_loads_6")
        self.gridLayout.addWidget(self.lineEdit_loads_6, 12, 10, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 15, 0, 1, 1)
        self.lineEdit_loads_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_loads_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_loads_7.setObjectName("lineEdit_loads_7")
        self.gridLayout.addWidget(self.lineEdit_loads_7, 14, 10, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 15, 6, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_angle, self.lineEdit_angle_2)
        Dialog.setTabOrder(self.lineEdit_angle_2, self.lineEdit_angle_3)
        Dialog.setTabOrder(self.lineEdit_angle_3, self.lineEdit_angle_4)
        Dialog.setTabOrder(self.lineEdit_angle_4, self.lineEdit_angle_5)
        Dialog.setTabOrder(self.lineEdit_angle_5, self.lineEdit_angle_6)
        Dialog.setTabOrder(self.lineEdit_angle_6, self.lineEdit_angle_7)
        Dialog.setTabOrder(self.lineEdit_angle_7, self.comboBx_selection)
        Dialog.setTabOrder(self.comboBx_selection, self.comboBx_selection_2)
        Dialog.setTabOrder(self.comboBx_selection_2, self.comboBx_selection_3)
        Dialog.setTabOrder(self.comboBx_selection_3, self.comboBx_selection_4)
        Dialog.setTabOrder(self.comboBx_selection_4, self.comboBx_selection_5)
        Dialog.setTabOrder(self.comboBx_selection_5, self.comboBx_selection_6)
        Dialog.setTabOrder(self.comboBx_selection_6, self.comboBx_selection_7)
        Dialog.setTabOrder(self.comboBx_selection_7, self.lineEdit_loads)
        Dialog.setTabOrder(self.lineEdit_loads, self.lineEdit_loads_2)
        Dialog.setTabOrder(self.lineEdit_loads_2, self.lineEdit_loads_3)
        Dialog.setTabOrder(self.lineEdit_loads_3, self.lineEdit_loads_4)
        Dialog.setTabOrder(self.lineEdit_loads_4, self.lineEdit_loads_5)
        Dialog.setTabOrder(self.lineEdit_loads_5, self.lineEdit_loads_6)
        Dialog.setTabOrder(self.lineEdit_loads_6, self.lineEdit_loads_7)
        Dialog.setTabOrder(self.lineEdit_loads_7, self.lineEdit_no_of_member_4)
        Dialog.setTabOrder(self.lineEdit_no_of_member_4, self.lineEdit_no_of_member_3)
        Dialog.setTabOrder(self.lineEdit_no_of_member_3, self.lineEdit_no_of_member_5)
        Dialog.setTabOrder(self.lineEdit_no_of_member_5, self.lineEdit_no_of_member_7)
        Dialog.setTabOrder(self.lineEdit_no_of_member_7, self.lineEdit_no_of_member_6)
        Dialog.setTabOrder(self.lineEdit_no_of_member_6, self.lineEdit_no_of_member)
        Dialog.setTabOrder(self.lineEdit_no_of_member, self.lineEdit_no_of_member_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Define members"))
        self.btn_save.setText(_translate("Dialog", "Save"))
        self.btn_reset.setText(_translate("Dialog", "Reset"))
        self.btn_close.setText(_translate("Dialog", "Close"))
        self.lineEdit_no_of_member_3.setPlaceholderText(_translate("Dialog", "3"))
        self.label_10.setText(_translate("Dialog", "Section type              Section"))
        self.label_9.setText(_translate("Dialog", "Maximum factored \n"
"axial force (kN)"))
        self.lineEdit_no_of_member_4.setPlaceholderText(_translate("Dialog", "4"))
        self.lineEdit_no_of_member_5.setPlaceholderText(_translate("Dialog", "5"))
        self.comboBx_selection_2.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_2.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_2.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_2.setItemText(3, _translate("Dialog", "Channel "))
        self.lineEdit_no_of_member_2.setPlaceholderText(_translate("Dialog", "2"))
        self.lineEdit_no_of_member.setPlaceholderText(_translate("Dialog", "1"))
        self.comboBx_selection_6.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_6.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_6.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_6.setItemText(3, _translate("Dialog", "Channel "))
        self.comboBx_selection_5.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_5.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_5.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_5.setItemText(3, _translate("Dialog", "Channel "))
        self.lineEdit_no_of_member_6.setPlaceholderText(_translate("Dialog", "6"))
        self.label_11.setText(_translate("Dialog", "Inclination\n"
"(degree)"))
        self.comboBx_selection_3.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_3.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_3.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_3.setItemText(3, _translate("Dialog", "Channel "))
        self.label_12.setText(_translate("Dialog", "Member"))
        self.comboBx_selection.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection.setItemText(3, _translate("Dialog", "Channel "))
        self.comboBx_selection_4.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_4.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_4.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_4.setItemText(3, _translate("Dialog", "Channel "))
        self.comboBx_selection_7.setItemText(0, _translate("Dialog", "Select type"))
        self.comboBx_selection_7.setItemText(1, _translate("Dialog", "Single Angle"))
        self.comboBx_selection_7.setItemText(2, _translate("Dialog", "Double Angle"))
        self.comboBx_selection_7.setItemText(3, _translate("Dialog", "Channel "))
        self.lineEdit_no_of_member_7.setPlaceholderText(_translate("Dialog", "7"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Selection()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
