# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flangespliceplate_inner.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlangespliceplateInner(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(273, 309)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_outer_plateHeight = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_outer_plateHeight.setFont(font)
        self.txt_outer_plateHeight.setReadOnly(True)
        self.txt_outer_plateHeight.setObjectName("txt_outer_plateHeight")
        self.gridLayout.addWidget(self.txt_outer_plateHeight, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.txt_plateCapacity = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateCapacity.setFont(font)
        self.txt_plateCapacity.setReadOnly(True)
        self.txt_plateCapacity.setObjectName("txt_plateCapacity")
        self.gridLayout.addWidget(self.txt_plateCapacity, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_164 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_164.setFont(font)
        self.label_164.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_164.setObjectName("label_164")
        self.gridLayout.addWidget(self.label_164, 8, 0, 1, 1)
        self.label_163 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_163.setObjectName("label_163")
        self.gridLayout.addWidget(self.label_163, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.txt_outer_plateWidth = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_outer_plateWidth.setFont(font)
        self.txt_outer_plateWidth.setReadOnly(True)
        self.txt_outer_plateWidth.setObjectName("txt_outer_plateWidth")
        self.gridLayout.addWidget(self.txt_outer_plateWidth, 2, 1, 1, 1)
        self.plateHeight = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight.setFont(font)
        self.plateHeight.setObjectName("plateHeight")
        self.gridLayout.addWidget(self.plateHeight, 1, 0, 1, 1)
        self.label_162 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_162.setFont(font)
        self.label_162.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_162.setObjectName("label_162")
        self.gridLayout.addWidget(self.label_162, 6, 0, 1, 1)
        self.txt_plateDemand = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateDemand.setFont(font)
        self.txt_plateDemand.setReadOnly(True)
        self.txt_plateDemand.setObjectName("txt_plateDemand")
        self.gridLayout.addWidget(self.txt_plateDemand, 7, 1, 1, 1)
        self.txt_inner_plateHeight = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_inner_plateHeight.setFont(font)
        self.txt_inner_plateHeight.setObjectName("txt_inner_plateHeight")
        self.gridLayout.addWidget(self.txt_inner_plateHeight, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.txt_inner_plateWidth = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_inner_plateWidth.setFont(font)
        self.txt_inner_plateWidth.setObjectName("txt_inner_plateWidth")
        self.gridLayout.addWidget(self.txt_inner_plateWidth, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Flange splice plate"))
        self.label_3.setText(_translate("Dialog", "Inner flange splice plate"))
        self.label.setText(_translate("Dialog", "Outer flange splice plate"))
        self.label_164.setText(_translate("Dialog", "<html><head/><body><p>Capacity (kN)</p></body></html>"))
        self.label_163.setText(_translate("Dialog", "<html><head/><body><p>Demand (kN)</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Width (mm)"))
        self.plateHeight.setText(_translate("Dialog", "Height (mm)"))
        self.label_162.setText(_translate("Dialog", "<html><head/><body><p>Strength</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Height (mm)"))
        self.label_5.setText(_translate("Dialog", "Width (mm)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_FlangespliceplateInner()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

