name: osdag-ifc-final
channels:
  - conda-forge
  - osdag
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pyside6=6.9.2
  - pythonocc-core=7.9.0
  - smesh=9.9.0.0
  - pandas
  - pylatex
  - click
  - pyyaml
  - sqlite
  - tbb
  - requests
  - markdown
  - openpyxl
  - matplotlib
  - osdag_latex_env=1.0.2
  - pip
  - pip:
      - ifcopenshell==0.8.4.post1
      - lark==1.3.1
      - pyqt5==5.15.11
