[workspace]
name = "Osdag"
version = "1.0.0"
description = "Pixi instructions for Osdag"
authors = ["Aathithya Sharan"]
preview = ["pixi-build"]
channels = ["conda-forge", "osdag"]
platforms = ["win-64"]

[dependencies]
python = "3.10.*"
numpy = "2.2.5"
openpyxl = "3.1.5"
pandas = "2.2.3"
pynput = "1.8.1"
pyqt = "5.15.10"
pythonocc-core = "7.8.1.1"
pylatex = "1.4.2"
pygithub = "2.6.1"
pyyaml = "6.0.2"
smesh = "9.9.0.0"
tbb = "2022.1.0"

[feature.editable.dependencies]
osdag = "2025.01.a.2"

[feature.editable.tasks]
install-editable = "pip install -e ."
osdag-editable = "osdag"

[feature.noneditable.dependencies]
osdag = "2025.01.a.2"

[feature.noneditable.tasks]
osdag = "osdag"

[environments]
dev = ["editable"]
default = ["noneditable"]
