# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OsdagMainPage.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1050, 593)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/Osdag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget::showMaximised()")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: #abc250;")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(4)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(40, -1, 40, -1)
        self.gridLayout_8.setHorizontalSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 10, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 8, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 16, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 14, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 12, 0, 1, 1)
        self.btn_connection = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connection.sizePolicy().hasHeightForWidth())
        self.btn_connection.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_connection.setFont(font)
        self.btn_connection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_connection.setMouseTracking(False)
        self.btn_connection.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_connection.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btn_connection.setAutoFillBackground(False)
        self.btn_connection.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"   \n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.btn_connection.setAutoDefault(True)
        self.btn_connection.setDefault(False)
        self.btn_connection.setFlat(False)
        self.btn_connection.setObjectName("btn_connection")
        self.gridLayout_8.addWidget(self.btn_connection, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 18, 0, 1, 1)
        self.btn_compression = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_compression.sizePolicy().hasHeightForWidth())
        self.btn_compression.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_compression.setFont(font)
        self.btn_compression.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}\n"
"")
        self.btn_compression.setAutoDefault(True)
        self.btn_compression.setObjectName("btn_compression")
        self.gridLayout_8.addWidget(self.btn_compression, 5, 0, 1, 1)
        self.btn_flexural = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_flexural.sizePolicy().hasHeightForWidth())
        self.btn_flexural.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_flexural.setFont(font)
        self.btn_flexural.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_flexural.setAutoDefault(True)
        self.btn_flexural.setObjectName("btn_flexural")
        self.gridLayout_8.addWidget(self.btn_flexural, 7, 0, 1, 1)
        self.btn_beamCol = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_beamCol.sizePolicy().hasHeightForWidth())
        self.btn_beamCol.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_beamCol.setFont(font)
        self.btn_beamCol.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_beamCol.setAutoDefault(True)
        self.btn_beamCol.setObjectName("btn_beamCol")
        self.gridLayout_8.addWidget(self.btn_beamCol, 9, 0, 1, 1)
        self.btn_plate = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_plate.sizePolicy().hasHeightForWidth())
        self.btn_plate.setSizePolicy(sizePolicy)
        self.btn_plate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plate.setFont(font)
        self.btn_plate.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_plate.setAutoDefault(True)
        self.btn_plate.setObjectName("btn_plate")
        self.gridLayout_8.addWidget(self.btn_plate, 11, 0, 1, 1)
        self.btn_truss = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_truss.sizePolicy().hasHeightForWidth())
        self.btn_truss.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_truss.setFont(font)
        self.btn_truss.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_truss.setAutoDefault(True)
        self.btn_truss.setObjectName("btn_truss")
        self.gridLayout_8.addWidget(self.btn_truss, 13, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem8, 20, 0, 1, 1)
        self.btn_3dframe = QtWidgets.QPushButton(self.frame)
        self.btn_3dframe.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3dframe.sizePolicy().hasHeightForWidth())
        self.btn_3dframe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3dframe.setFont(font)
        self.btn_3dframe.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_3dframe.setAutoDefault(True)
        self.btn_3dframe.setObjectName("btn_3dframe")
        self.gridLayout_8.addWidget(self.btn_3dframe, 17, 0, 1, 1)
        self.btn_2dframe = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2dframe.sizePolicy().hasHeightForWidth())
        self.btn_2dframe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2dframe.setFont(font)
        self.btn_2dframe.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_2dframe.setAutoDefault(True)
        self.btn_2dframe.setObjectName("btn_2dframe")
        self.gridLayout_8.addWidget(self.btn_2dframe, 15, 0, 1, 1)
        self.btn_tension = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tension.sizePolicy().hasHeightForWidth())
        self.btn_tension.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tension.setFont(font)
        self.btn_tension.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"   \n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"\n"
"}\n"
"")
        self.btn_tension.setAutoDefault(True)
        self.btn_tension.setDefault(True)
        self.btn_tension.setObjectName("btn_tension")
        self.gridLayout_8.addWidget(self.btn_tension, 3, 0, 1, 1)
        self.btn_groupdesign = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_groupdesign.sizePolicy().hasHeightForWidth())
        self.btn_groupdesign.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_groupdesign.setFont(font)
        self.btn_groupdesign.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_groupdesign.setAutoDefault(True)
        self.btn_groupdesign.setObjectName("btn_groupdesign")
        self.gridLayout_8.addWidget(self.btn_groupdesign, 19, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.comboBox_help = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_help.sizePolicy().hasHeightForWidth())
        self.comboBox_help.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 90, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.comboBox_help.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.comboBox_help.setFont(font)
        self.comboBox_help.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox_help.setAutoFillBackground(False)
        self.comboBox_help.setStyleSheet("QComboBox::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"")
        self.comboBox_help.setFrame(True)
        self.comboBox_help.setObjectName("comboBox_help")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.gridLayout.addWidget(self.comboBox_help, 1, 0, 1, 1)
        self.myStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myStackedWidget.sizePolicy().hasHeightForWidth())
        self.myStackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.myStackedWidget.setFont(font)
        self.myStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.myStackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.myStackedWidget.setObjectName("myStackedWidget")
        self.Osdagpage = QtWidgets.QWidget()
        self.Osdagpage.setObjectName("Osdagpage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Osdagpage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_OsdagHeader = QtWidgets.QLabel(self.Osdagpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_OsdagHeader.sizePolicy().hasHeightForWidth())
        self.lbl_OsdagHeader.setSizePolicy(sizePolicy)
        self.lbl_OsdagHeader.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_OsdagHeader.setMaximumSize(QtCore.QSize(1200, 300))
        self.lbl_OsdagHeader.setText("")
        self.lbl_OsdagHeader.setPixmap(QtGui.QPixmap(":/newPrefix/images/Osdag_header.png"))
        self.lbl_OsdagHeader.setScaledContents(True)
        self.lbl_OsdagHeader.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbl_OsdagHeader.setWordWrap(False)
        self.lbl_OsdagHeader.setObjectName("lbl_OsdagHeader")
        self.gridLayout_2.addWidget(self.lbl_OsdagHeader, 0, 0, 2, 2)
        spacerItem11 = QtWidgets.QSpacerItem(145, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 646, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 3, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 3, 2, 1, 1)
        self.lbl_fosseelogo = QtWidgets.QLabel(self.Osdagpage)
        self.lbl_fosseelogo.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_fosseelogo.setMaximumSize(QtCore.QSize(250, 92))
        self.lbl_fosseelogo.setText("")
        self.lbl_fosseelogo.setPixmap(QtGui.QPixmap(":/newPrefix/images/Fossee_logo.png"))
        self.lbl_fosseelogo.setScaledContents(True)
        self.lbl_fosseelogo.setObjectName("lbl_fosseelogo")
        self.gridLayout_2.addWidget(self.lbl_fosseelogo, 3, 0, 1, 1)
        self.lbl_iitblogo = QtWidgets.QLabel(self.Osdagpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_iitblogo.sizePolicy().hasHeightForWidth())
        self.lbl_iitblogo.setSizePolicy(sizePolicy)
        self.lbl_iitblogo.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_iitblogo.setText("")
        self.lbl_iitblogo.setPixmap(QtGui.QPixmap(":/newPrefix/images/logoiitb.png"))
        self.lbl_iitblogo.setScaledContents(True)
        self.lbl_iitblogo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_iitblogo.setObjectName("lbl_iitblogo")
        self.gridLayout_2.addWidget(self.lbl_iitblogo, 3, 3, 1, 1)
        self.myStackedWidget.addWidget(self.Osdagpage)
        self.Connectionpage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connectionpage.sizePolicy().hasHeightForWidth())
        self.Connectionpage.setSizePolicy(sizePolicy)
        self.Connectionpage.setObjectName("Connectionpage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.Connectionpage)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.mytabWidget = QtWidgets.QTabWidget(self.Connectionpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mytabWidget.sizePolicy().hasHeightForWidth())
        self.mytabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.mytabWidget.setFont(font)
        self.mytabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mytabWidget.setStyleSheet("QTabBar::tab {\n"
"    margin-right: 10;\n"
" }\n"
"\n"
"QTabBar::tab::selected{\n"
"    background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QTabBar::tab::hover{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"height: 40px;\n"
"width: 200px;\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"border-top-left-radius: 2px ;\n"
"border-top-right-radius: 2px ;\n"
"border-bottom-left-radius: 0px ;\n"
"border-bottom-right-radius: 0px ;\n"
"}\n"
" ")
        self.mytabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.mytabWidget.setDocumentMode(True)
        self.mytabWidget.setTabsClosable(False)
        self.mytabWidget.setMovable(False)
        self.mytabWidget.setObjectName("mytabWidget")
        self.tab1_shearconnection = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setItalic(False)
        self.tab1_shearconnection.setFont(font)
        self.tab1_shearconnection.setObjectName("tab1_shearconnection")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab1_shearconnection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 0, 6, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab1_shearconnection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.rdbtn_finplate = QtWidgets.QRadioButton(self.tab1_shearconnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_finplate.sizePolicy().hasHeightForWidth())
        self.rdbtn_finplate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.rdbtn_finplate.setFont(font)
        self.rdbtn_finplate.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdbtn_finplate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_finplate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ResourceFiles/images/finplate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_finplate.setIcon(icon1)
        self.rdbtn_finplate.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_finplate.setCheckable(True)
        self.rdbtn_finplate.setObjectName("rdbtn_finplate")
        self.verticalLayout.addWidget(self.rdbtn_finplate)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 1, 1, 3)
        spacerItem18 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 1, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab1_shearconnection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.rdbtn_cleat = QtWidgets.QRadioButton(self.tab1_shearconnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_cleat.sizePolicy().hasHeightForWidth())
        self.rdbtn_cleat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.rdbtn_cleat.setFont(font)
        self.rdbtn_cleat.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdbtn_cleat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_cleat.setStyleSheet("QRadioButton ")
        self.rdbtn_cleat.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ResourceFiles/images/cleatAngle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_cleat.setIcon(icon2)
        self.rdbtn_cleat.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_cleat.setObjectName("rdbtn_cleat")
        self.verticalLayout_3.addWidget(self.rdbtn_cleat)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 5, 1, 3)
        spacerItem19 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 1, 8, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab1_shearconnection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.rdbtn_endplate = QtWidgets.QRadioButton(self.tab1_shearconnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_endplate.sizePolicy().hasHeightForWidth())
        self.rdbtn_endplate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.rdbtn_endplate.setFont(font)
        self.rdbtn_endplate.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdbtn_endplate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_endplate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ResourceFiles/images/endplate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_endplate.setIcon(icon3)
        self.rdbtn_endplate.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_endplate.setObjectName("rdbtn_endplate")
        self.verticalLayout_4.addWidget(self.rdbtn_endplate)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 1, 1, 3)
        spacerItem21 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 2, 4, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab1_shearconnection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.rdbtn_seat = QtWidgets.QRadioButton(self.tab1_shearconnection)
        self.rdbtn_seat.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdbtn_seat.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/seatedAngle1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_seat.setIcon(icon4)
        self.rdbtn_seat.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_seat.setObjectName("rdbtn_seat")
        self.verticalLayout_5.addWidget(self.rdbtn_seat)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 2, 5, 1, 3)
        spacerItem22 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 2, 8, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem23, 3, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem24, 3, 7, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem25, 4, 3, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.tab1_shearconnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(190, 30))
        self.btn_start.setMaximumSize(QtCore.QSize(190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_start.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_start.setCheckable(False)
        self.btn_start.setAutoExclusive(False)
        self.btn_start.setAutoDefault(True)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_3.addWidget(self.btn_start, 4, 4, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem26, 4, 5, 1, 1)
        self.mytabWidget.addTab(self.tab1_shearconnection, "")
        self.tab2_momentconnection = QtWidgets.QWidget()
        self.tab2_momentconnection.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab2_momentconnection.setObjectName("tab2_momentconnection")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab2_momentconnection)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mytabWidget_2 = QtWidgets.QTabWidget(self.tab2_momentconnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mytabWidget_2.sizePolicy().hasHeightForWidth())
        self.mytabWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mytabWidget_2.setFont(font)
        self.mytabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mytabWidget_2.setStyleSheet("QTabBar::tab {\n"
"    margin-right: 10;\n"
" }\n"
"\n"
"QTabBar::tab::selected{\n"
"    background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QTabBar::tab::hover{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"height: 35px;\n"
"width: 150px;\n"
"background-color: #9e6869;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"border-top-left-radius: 2px ;\n"
"border-top-right-radius: 2px ;\n"
"border-bottom-left-radius: 0px ;\n"
"border-bottom-right-radius: 0px ;\n"
"}")
        self.mytabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.mytabWidget_2.setDocumentMode(True)
        self.mytabWidget_2.setObjectName("mytabWidget_2")
        self.tab_beamtobeam = QtWidgets.QWidget()
        self.tab_beamtobeam.setObjectName("tab_beamtobeam")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_beamtobeam)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_65 = QtWidgets.QLabel(self.tab_beamtobeam)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_51.addWidget(self.label_65)
        self.rdbtn_coverplate_7 = QtWidgets.QRadioButton(self.tab_beamtobeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_coverplate_7.sizePolicy().hasHeightForWidth())
        self.rdbtn_coverplate_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdbtn_coverplate_7.setFont(font)
        self.rdbtn_coverplate_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_coverplate_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/coverplate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_coverplate_7.setIcon(icon5)
        self.rdbtn_coverplate_7.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_coverplate_7.setObjectName("rdbtn_coverplate_7")
        self.verticalLayout_51.addWidget(self.rdbtn_coverplate_7)
        self.gridLayout_4.addLayout(self.verticalLayout_51, 0, 1, 1, 1)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.label_66 = QtWidgets.QLabel(self.tab_beamtobeam)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_52.addWidget(self.label_66)
        self.rdbtn_endplate_ext_7 = QtWidgets.QRadioButton(self.tab_beamtobeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_endplate_ext_7.sizePolicy().hasHeightForWidth())
        self.rdbtn_endplate_ext_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdbtn_endplate_ext_7.setFont(font)
        self.rdbtn_endplate_ext_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_endplate_ext_7.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/extended.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_endplate_ext_7.setIcon(icon6)
        self.rdbtn_endplate_ext_7.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_endplate_ext_7.setObjectName("rdbtn_endplate_ext_7")
        self.verticalLayout_52.addWidget(self.rdbtn_endplate_ext_7)
        self.gridLayout_4.addLayout(self.verticalLayout_52, 0, 3, 1, 1)
        self.btn_start_2 = QtWidgets.QPushButton(self.tab_beamtobeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_2.sizePolicy().hasHeightForWidth())
        self.btn_start_2.setSizePolicy(sizePolicy)
        self.btn_start_2.setMinimumSize(QtCore.QSize(190, 30))
        self.btn_start_2.setMaximumSize(QtCore.QSize(190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start_2.setFont(font)
        self.btn_start_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_start_2.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_start_2.setCheckable(False)
        self.btn_start_2.setAutoExclusive(False)
        self.btn_start_2.setAutoDefault(True)
        self.btn_start_2.setObjectName("btn_start_2")
        self.gridLayout_4.addWidget(self.btn_start_2, 2, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem28, 0, 2, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 2, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem30, 1, 2, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem31, 2, 3, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 0, 4, 1, 1)
        self.mytabWidget_2.addTab(self.tab_beamtobeam, "")
        self.tab_beamtocolumn = QtWidgets.QWidget()
        self.tab_beamtocolumn.setObjectName("tab_beamtocolumn")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_beamtocolumn)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.label_67 = QtWidgets.QLabel(self.tab_beamtocolumn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_53.addWidget(self.label_67)
        self.rdbtn_endplate_bc_7 = QtWidgets.QRadioButton(self.tab_beamtocolumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdbtn_endplate_bc_7.sizePolicy().hasHeightForWidth())
        self.rdbtn_endplate_bc_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdbtn_endplate_bc_7.setFont(font)
        self.rdbtn_endplate_bc_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdbtn_endplate_bc_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ResourceFiles/images/beam_column_endplate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtn_endplate_bc_7.setIcon(icon7)
        self.rdbtn_endplate_bc_7.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_endplate_bc_7.setObjectName("rdbtn_endplate_bc_7")
        self.verticalLayout_53.addWidget(self.rdbtn_endplate_bc_7)
        self.gridLayout_9.addLayout(self.verticalLayout_53, 1, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem33, 3, 2, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem34, 3, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem35, 2, 0, 1, 1)
        self.btn_start_3 = QtWidgets.QPushButton(self.tab_beamtocolumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_3.sizePolicy().hasHeightForWidth())
        self.btn_start_3.setSizePolicy(sizePolicy)
        self.btn_start_3.setMinimumSize(QtCore.QSize(190, 30))
        self.btn_start_3.setMaximumSize(QtCore.QSize(190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start_3.setFont(font)
        self.btn_start_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_start_3.setStyleSheet("QPushButton::hover\n"
"{\n"
"   background-color: #d97f7f;\n"
"   color:#000000 ;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #925a5b;\n"
"color:#ffffff;\n"
"}")
        self.btn_start_3.setCheckable(False)
        self.btn_start_3.setAutoExclusive(False)
        self.btn_start_3.setAutoDefault(True)
        self.btn_start_3.setObjectName("btn_start_3")
        self.gridLayout_9.addWidget(self.btn_start_3, 3, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem36, 1, 1, 1, 2)
        self.mytabWidget_2.addTab(self.tab_beamtocolumn, "")
        self.tab_columntocolumn = QtWidgets.QWidget()
        self.tab_columntocolumn.setObjectName("tab_columntocolumn")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_columntocolumn)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem37, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_columntocolumn)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 1, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem38, 1, 2, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem39, 2, 1, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem40, 0, 1, 1, 1)
        self.mytabWidget_2.addTab(self.tab_columntocolumn, "")
        self.tab_PEB = QtWidgets.QWidget()
        self.tab_PEB.setObjectName("tab_PEB")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_PEB)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_12 = QtWidgets.QLabel(self.tab_PEB)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 1, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem41, 1, 2, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem42, 0, 1, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem43, 1, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem44, 2, 1, 1, 1)
        self.mytabWidget_2.addTab(self.tab_PEB, "")
        self.gridLayout_7.addWidget(self.mytabWidget_2, 0, 1, 1, 1)
        self.mytabWidget.addTab(self.tab2_momentconnection, "")
        self.tab3_trussconnection = QtWidgets.QWidget()
        self.tab3_trussconnection.setObjectName("tab3_trussconnection")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab3_trussconnection)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem45, 1, 0, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem46, 0, 1, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem47, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab3_trussconnection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 1, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem48, 2, 1, 1, 1)
        self.mytabWidget.addTab(self.tab3_trussconnection, "")
        self.gridLayout_10.addWidget(self.mytabWidget, 0, 0, 1, 1)
        self.myStackedWidget.addWidget(self.Connectionpage)
        self.beamtobeampage = QtWidgets.QWidget()
        self.beamtobeampage.setEnabled(False)
        self.beamtobeampage.setObjectName("beamtobeampage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.beamtobeampage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.beamtobeampage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 3, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(20, 358, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem49, 4, 2, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem50, 2, 4, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem51, 3, 1, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem52, 3, 3, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(382, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem53, 5, 0, 1, 2)
        self.rdbtn_endplate_ext = QtWidgets.QRadioButton(self.beamtobeampage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdbtn_endplate_ext.setFont(font)
        self.rdbtn_endplate_ext.setText("")
        self.rdbtn_endplate_ext.setIcon(icon6)
        self.rdbtn_endplate_ext.setIconSize(QtCore.QSize(300, 300))
        self.rdbtn_endplate_ext.setObjectName("rdbtn_endplate_ext")
        self.gridLayout_5.addWidget(self.rdbtn_endplate_ext, 2, 3, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(364, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem54, 5, 3, 1, 2)
        spacerItem55 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem55, 6, 2, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem56, 0, 1, 1, 1)
        self.myStackedWidget.addWidget(self.beamtobeampage)
        self.page = QtWidgets.QWidget()
        self.page.setEnabled(False)
        self.page.setObjectName("page")
        self.myStackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.myStackedWidget, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_help.setCurrentIndex(0)
        self.myStackedWidget.setCurrentIndex(1)
        self.mytabWidget.setCurrentIndex(0)
        self.mytabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Osdag"))
        self.btn_connection.setToolTip(_translate("MainWindow", "Ctrl+Shift+C"))
        self.btn_connection.setText(_translate("MainWindow", "Connection"))
        self.btn_connection.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.btn_compression.setToolTip(_translate("MainWindow", "Ctrl+Shift+M"))
        self.btn_compression.setText(_translate("MainWindow", "      Compression Member       "))
        self.btn_compression.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))
        self.btn_flexural.setToolTip(_translate("MainWindow", "Ctrl+Shift+F"))
        self.btn_flexural.setText(_translate("MainWindow", "Flexural Member"))
        self.btn_flexural.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.btn_beamCol.setToolTip(_translate("MainWindow", "Ctrl+Shift+B"))
        self.btn_beamCol.setText(_translate("MainWindow", "Beam-Column"))
        self.btn_beamCol.setShortcut(_translate("MainWindow", "Ctrl+Shift+B"))
        self.btn_plate.setToolTip(_translate("MainWindow", "Ctrl+Shift+P"))
        self.btn_plate.setText(_translate("MainWindow", "Plate Girder"))
        self.btn_plate.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.btn_truss.setToolTip(_translate("MainWindow", "Ctrl+Shift+R"))
        self.btn_truss.setText(_translate("MainWindow", "Truss"))
        self.btn_truss.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.btn_3dframe.setToolTip(_translate("MainWindow", "Ctrl+3"))
        self.btn_3dframe.setText(_translate("MainWindow", "3D Frame"))
        self.btn_3dframe.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.btn_2dframe.setToolTip(_translate("MainWindow", "Ctrl+2"))
        self.btn_2dframe.setText(_translate("MainWindow", "2D Frame"))
        self.btn_2dframe.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.btn_tension.setToolTip(_translate("MainWindow", "Ctrl+Shift+T"))
        self.btn_tension.setText(_translate("MainWindow", "Tension Member"))
        self.btn_tension.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.btn_groupdesign.setToolTip(_translate("MainWindow", "Ctrl+Shift+D"))
        self.btn_groupdesign.setText(_translate("MainWindow", "Group Design"))
        self.btn_groupdesign.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.comboBox_help.setItemText(0, _translate("MainWindow", "Help"))
        self.comboBox_help.setItemText(1, _translate("MainWindow", "Video Tutorials"))
        self.comboBox_help.setItemText(2, _translate("MainWindow", "Design Examples"))
        self.comboBox_help.setItemText(3, _translate("MainWindow", "Ask Us a Question"))
        self.comboBox_help.setItemText(4, _translate("MainWindow", "About Osdag"))
        self.label_2.setToolTip(_translate("MainWindow", "Shift+F"))
        self.label_2.setText(_translate("MainWindow", "Fin Plate"))
        self.rdbtn_finplate.setShortcut(_translate("MainWindow", "Shift+F"))
        self.label_3.setToolTip(_translate("MainWindow", "Shift+C"))
        self.label_3.setText(_translate("MainWindow", "Cleat Angle"))
        self.rdbtn_cleat.setShortcut(_translate("MainWindow", "Shift+C"))
        self.label_4.setToolTip(_translate("MainWindow", "Shift+E"))
        self.label_4.setText(_translate("MainWindow", "End Plate"))
        self.rdbtn_endplate.setShortcut(_translate("MainWindow", "Shift+E"))
        self.label_5.setToolTip(_translate("MainWindow", "Shift+S"))
        self.label_5.setText(_translate("MainWindow", "Seated Angle"))
        self.rdbtn_seat.setShortcut(_translate("MainWindow", "Shift+S"))
        self.btn_start.setToolTip(_translate("MainWindow", "Enter"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_start.setShortcut(_translate("MainWindow", "Return"))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab1_shearconnection), _translate("MainWindow", "Shear Connection"))
        self.label_65.setText(_translate("MainWindow", "Cover Plate Connection"))
        self.label_66.setText(_translate("MainWindow", "End Plate Connection"))
        self.btn_start_2.setToolTip(_translate("MainWindow", "Enter"))
        self.btn_start_2.setText(_translate("MainWindow", "Start"))
        self.btn_start_2.setShortcut(_translate("MainWindow", "Return"))
        self.mytabWidget_2.setTabText(self.mytabWidget_2.indexOf(self.tab_beamtobeam), _translate("MainWindow", "Beam To Beam"))
        self.label_67.setText(_translate("MainWindow", "End Plate Connection"))
        self.btn_start_3.setToolTip(_translate("MainWindow", "Enter"))
        self.btn_start_3.setText(_translate("MainWindow", "Start"))
        self.btn_start_3.setShortcut(_translate("MainWindow", "Return"))
        self.mytabWidget_2.setTabText(self.mytabWidget_2.indexOf(self.tab_beamtocolumn), _translate("MainWindow", "Beam To Column"))
        self.label_13.setText(_translate("MainWindow", "This module is not available in the current version."))
        self.mytabWidget_2.setTabText(self.mytabWidget_2.indexOf(self.tab_columntocolumn), _translate("MainWindow", "Column To Column"))
        self.label_12.setText(_translate("MainWindow", "This module is not available in the current version."))
        self.mytabWidget_2.setTabText(self.mytabWidget_2.indexOf(self.tab_PEB), _translate("MainWindow", "PEB"))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab2_momentconnection), _translate("MainWindow", "Moment Connection"))
        self.label_6.setText(_translate("MainWindow", "This module is not available in the current version."))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab3_trussconnection), _translate("MainWindow", "Truss Connection"))
        self.label_7.setText(_translate("MainWindow", "End Plate Connection"))
import osdagMainPageIcons_rc
