# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_OsdagSectionModeller.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.ui_section_parameters import Ui_SectionParameters

class Ui_OsdagSectionModeller(object):
    def setupUi(self,Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(901, 790)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(901, 0))
        Dialog.setMaximumSize(QtCore.QSize(901, 825))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.design_section = QtWidgets.QFrame(Dialog)
        self.design_section.setStyleSheet("QFrame{\n"
"background:#ffffff;\n"
"}")
        self.design_section.setFrameShape(QtWidgets.QFrame.Box)
        self.design_section.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.design_section.setLineWidth(3)
        self.design_section.setObjectName("design_section")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.design_section)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label = QtWidgets.QLabel(self.design_section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background:rgb(135, 135, 135);\n"
"color:#ffffff;\n"
"}")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_17.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(75, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.section_type_combobox = QtWidgets.QComboBox(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.section_type_combobox.setFont(font)
        self.section_type_combobox.setObjectName("section_type_combobox")
        self.section_type_combobox.addItem("")
        self.section_type_combobox.addItem("")
        self.section_type_combobox.addItem("")
        self.section_type_combobox.addItem("")
        self.section_type_combobox.addItem("")
        self.section_type_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.section_type_combobox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed) 
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.section_template_combobox = QtWidgets.QComboBox(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.section_template_combobox.setFont(font)
        self.section_template_combobox.setObjectName("section_template_combobox")
        self.section_template_combobox.addItem("")
        self.horizontalLayout_3.addWidget(self.section_template_combobox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.section_designation_lineEdit = QtWidgets.QLineEdit(self.design_section)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.section_designation_lineEdit.setFont(font)
        self.section_designation_lineEdit.setInputMask("")
        self.section_designation_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.section_designation_lineEdit.setObjectName("section_designation_lineEdit")
        self.verticalLayout_3.addWidget(self.section_designation_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_17.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.design_section)
        self.occ = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.occ.setFont(font)
        self.occ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.occ.setStyleSheet("QFrame{\n"
"background:#ffffff;\n"
"}")
        self.occ.setFrameShape(QtWidgets.QFrame.Box)
        self.occ.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.occ.setLineWidth(3)
        self.occ.setObjectName("occ")
        self.horizontalLayout.addWidget(self.occ)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.section_properties = QtWidgets.QFrame(Dialog)
        self.section_properties.setStyleSheet("QFrame{\n"
"background:#ffffff;\n"
"}")
        self.section_properties.setFrameShape(QtWidgets.QFrame.Box)
        self.section_properties.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.section_properties.setLineWidth(3)
        self.section_properties.setObjectName("section_properties")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.section_properties)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.section_properties)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"background:rgb(135, 135, 135);\n"
"color:#ffffff;\n"
"}")
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_16.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding) 
        self.verticalLayout_16.addItem(spacerItem4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(172, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.Area = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Area.setFont(font)
        self.Area.setInputMask("")
        self.Area.setAlignment(QtCore.Qt.AlignCenter)
        self.Area.setObjectName("Area")
        self.horizontalLayout_9.addWidget(self.Area)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.line_6 = QtWidgets.QFrame(self.section_properties)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_14.addWidget(self.line_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RG1 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RG1.setFont(font)
        self.RG1.setInputMask("")
        self.RG1.setAlignment(QtCore.Qt.AlignCenter)
        self.RG1.setObjectName("RG1")
        self.verticalLayout_4.addWidget(self.RG1)
        self.RG2 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RG2.setFont(font)
        self.RG2.setInputMask("")
        self.RG2.setAlignment(QtCore.Qt.AlignCenter)
        self.RG2.setObjectName("RG2")
        self.verticalLayout_4.addWidget(self.RG2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.section_properties)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_14.addWidget(self.line_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem7 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ESM1 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ESM1.setFont(font)
        self.ESM1.setInputMask("")
        self.ESM1.setAlignment(QtCore.Qt.AlignCenter)
        self.ESM1.setObjectName("ESM1")
        self.verticalLayout_5.addWidget(self.ESM1)
        self.ESM2 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ESM2.setFont(font)
        self.ESM2.setInputMask("")
        self.ESM2.setAlignment(QtCore.Qt.AlignCenter)
        self.ESM2.setObjectName("ESM2")
        self.verticalLayout_5.addWidget(self.ESM2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.Centroid_box = QtWidgets.QFrame(self.section_properties)
        self.Centroid_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Centroid_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Centroid_box.setObjectName("Centroid_box")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Centroid_box)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.line_4 = QtWidgets.QFrame(self.Centroid_box)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_18.addWidget(self.line_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.Centroid_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem8 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(22)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.Centroid_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.Centroid_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.C1 = QtWidgets.QLineEdit(self.Centroid_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.C1.setFont(font)
        self.C1.setInputMask("")
        self.C1.setAlignment(QtCore.Qt.AlignCenter)
        self.C1.setObjectName("C1")
        self.verticalLayout_6.addWidget(self.C1)
        self.C2 = QtWidgets.QLineEdit(self.Centroid_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.C2.setFont(font)
        self.C2.setInputMask("")
        self.C2.setAlignment(QtCore.Qt.AlignCenter)
        self.C2.setObjectName("C2")
        self.verticalLayout_6.addWidget(self.C2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addWidget(self.Centroid_box)
        self.horizontalLayout_15.addLayout(self.verticalLayout_14)
        self.line = QtWidgets.QFrame(self.section_properties)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_15.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.section_properties)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_15.addWidget(self.line_2)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        spacerItem9 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.MI_label_1 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_1.setFont(font)
        self.MI_label_1.setObjectName("MI_label_1")
        self.verticalLayout_12.addWidget(self.MI_label_1)
        self.MI_label_2 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_2.setFont(font)
        self.MI_label_2.setObjectName("MI_label_2")
        self.verticalLayout_12.addWidget(self.MI_label_2)
        self.MI_label_3 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_3.setFont(font)
        self.MI_label_3.setObjectName("MI_label_3")
        self.verticalLayout_12.addWidget(self.MI_label_3)
        self.MI_label_4 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_4.setFont(font)
        self.MI_label_4.setObjectName("MI_label_4")
        self.verticalLayout_12.addWidget(self.MI_label_4)
        self.MI_label_5 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_5.setFont(font)
        self.MI_label_5.setObjectName("MI_label_5")
        self.verticalLayout_12.addWidget(self.MI_label_5)
        self.MI_label_6 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_label_6.setFont(font)
        self.MI_label_6.setObjectName("MI_label_6")
        self.verticalLayout_12.addWidget(self.MI_label_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.MI_text_1 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_1.setFont(font)
        self.MI_text_1.setInputMask("")
        self.MI_text_1.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_1.setObjectName("MI_text_1")
        self.verticalLayout_13.addWidget(self.MI_text_1)
        self.MI_text_2 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_2.setFont(font)
        self.MI_text_2.setInputMask("")
        self.MI_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_2.setObjectName("MI_text_2")
        self.verticalLayout_13.addWidget(self.MI_text_2)
        self.MI_text_3 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_3.setFont(font)
        self.MI_text_3.setInputMask("")
        self.MI_text_3.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_3.setObjectName("MI_text_3")
        self.verticalLayout_13.addWidget(self.MI_text_3)
        self.MI_text_4 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_4.setFont(font)
        self.MI_text_4.setInputMask("")
        self.MI_text_4.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_4.setObjectName("MI_text_4")
        self.verticalLayout_13.addWidget(self.MI_text_4)
        self.MI_text_5 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_5.setFont(font)
        self.MI_text_5.setInputMask("")
        self.MI_text_5.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_5.setObjectName("MI_text_5")
        self.verticalLayout_13.addWidget(self.MI_text_5)
        self.MI_text_6 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MI_text_6.setFont(font)
        self.MI_text_6.setInputMask("")
        self.MI_text_6.setAlignment(QtCore.Qt.AlignCenter)
        self.MI_text_6.setObjectName("MI_text_6")
        self.verticalLayout_13.addWidget(self.MI_text_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.line_3 = QtWidgets.QFrame(self.section_properties)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_15.addWidget(self.line_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        spacerItem10 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.PSM_label_1 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_label_1.setFont(font)
        self.PSM_label_1.setObjectName("PSM_label_1")
        self.verticalLayout_10.addWidget(self.PSM_label_1)
        self.PSM_label_2 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_label_2.setFont(font)
        self.PSM_label_2.setObjectName("PSM_label_2")
        self.verticalLayout_10.addWidget(self.PSM_label_2)
        self.PSM_label_3 = QtWidgets.QLabel(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_label_3.setFont(font)
        self.PSM_label_3.setObjectName("PSM_label_3")
        self.verticalLayout_10.addWidget(self.PSM_label_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.PSM_text_1 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_text_1.setFont(font)
        self.PSM_text_1.setInputMask("")
        self.PSM_text_1.setAlignment(QtCore.Qt.AlignCenter)
        self.PSM_text_1.setObjectName("PSM_text_1")
        self.verticalLayout_11.addWidget(self.PSM_text_1)
        self.PSM_text_2 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_text_2.setFont(font)
        self.PSM_text_2.setInputMask("")
        self.PSM_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PSM_text_2.setObjectName("PSM_text_2")
        self.verticalLayout_11.addWidget(self.PSM_text_2)
        self.PSM_text_3 = QtWidgets.QLineEdit(self.section_properties)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PSM_text_3.setFont(font)
        self.PSM_text_3.setInputMask("")
        self.PSM_text_3.setAlignment(QtCore.Qt.AlignCenter)
        self.PSM_text_3.setObjectName("PSM_text_3")
        self.verticalLayout_11.addWidget(self.PSM_text_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_16.addItem(spacerItem11)
        self.verticalLayout.addWidget(self.section_properties)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem12)
        self.HLayout_Buttons = QtWidgets.QHBoxLayout()
        self.HLayout_Buttons.setObjectName("HLayout_Buttons")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_Buttons.addItem(spacerItem13)
        self.saveBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.HLayout_Buttons.addWidget(self.saveBtn)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_Buttons.addItem(spacerItem14)
        self.exportBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.HLayout_Buttons.addWidget(self.exportBtn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_Buttons.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.HLayout_Buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.section_type_combobox.currentIndexChanged.connect(self.type_change)
        self.section_template_combobox.currentIndexChanged.connect(self.template_change)
        self.section_designation_lineEdit.setValidator(QtGui.QRegExpValidator(
            QtCore.QRegExp("[a-zA-Z0-9@_]*"), self.section_designation_lineEdit
        ))
        self.disable_usability(True)

    def disable_usability(self,toggle):
            self.section_properties.setDisabled(toggle)
            self.saveBtn.setDisabled(toggle)
            self.exportBtn.setDisabled(toggle)

    def type_change(self):
        index_type=self.section_type_combobox.currentIndex()
        self.disable_usability(True)
        if(index_type in [1,4,5]):
                self.Centroid_box.hide()
                self.MI_label_3.hide()
                self.MI_text_3.hide()
                self.MI_label_4.hide()
                self.MI_text_4.hide()
                self.MI_label_5.hide()
                self.MI_text_5.hide()
                self.MI_label_6.hide()
                self.MI_text_6.hide()
                self.PSM_label_3.hide()
                self.PSM_text_3.hide()
        elif(index_type==2):
                self.MI_label_3.show()
                self.MI_text_3.show()
                self.MI_label_4.hide()
                self.MI_text_4.hide()
                self.MI_label_5.hide()
                self.MI_text_5.hide()
                self.MI_label_6.hide()
                self.MI_text_6.hide()
                self.PSM_label_3.show()
                self.PSM_text_3.show()
                self.MI_label_3.setText('Czz:')

        elif(index_type==3):
                self.Centroid_box.show()
                self.MI_label_3.show()
                self.MI_text_3.show()
                self.MI_label_4.show()
                self.MI_text_4.show()
                self.MI_label_5.show()
                self.MI_text_5.show()
                self.MI_label_6.show()
                self.MI_text_6.show()
                self.PSM_label_3.hide()
                self.PSM_text_3.hide()
                self.MI_label_3.setText('Ixy:')
        
        templates={
                0:[],
                1:['I I Side by Side'],
                2:['[ ] Face to Face','] [ Back to Back'],
                3:[
                        u'\u256c'+' Star Angles-4 Angles',
                        u'\u2309'+u'\u2308'+'Star Angles-2 Angles',
                        u'\u230d'+u'\u230e'+'Star Angles-2 Angles',
                        u'\u22a7'+'  Star Angles-2 Angles',
                        u'\u26f6'+' Box Section-4 Angles'
                ],
                4:[
                        u'\u02e1'+'I'+u'\u02e1'+'  I-Section with Stiffening',
                        u'\ua585'+' I-Section from Plates',
                        'Built up SHS/RHS',
                ],
                5:['I & Channel on One Flange','I & Channel on Both Flange'],
        }[index_type]
        self.section_template_combobox.blockSignals(True)
        self.section_template_combobox.clear()
        self.section_template_combobox.addItem('-------Select Template-------')
        self.section_template_combobox.addItems(templates)
        self.section_template_combobox.blockSignals(False)

    def template_change(self):
        index_type=self.section_type_combobox.currentIndex()
        index_template=self.section_template_combobox.currentIndex()
        if(index_template==0):
                self.disable_usability(True)
                return
        else:
                self.SectionParameters=Ui_SectionParameters()
                dialog=QtWidgets.QDialog()
                self.SectionParameters.setupUi(dialog)
                dialog.exec()

        self.disable_usability(False)
        if(index_type==2):
                if(index_template==1):
                                self.Centroid_box.hide()                        
                elif(index_template==2):
                                self.Centroid_box.show()


    def retranslateUi(self,Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Osdag Section Modeller"))
        self.label.setText(_translate("Dialog", "Design Section"))
        self.label_2.setText(_translate("Dialog", "Section Type:"))
        self.section_type_combobox.setItemText(0, _translate("Dialog", "---------Select Type---------"))
        self.section_type_combobox.setItemText(1, _translate("Dialog", "I-Section"))
        self.section_type_combobox.setItemText(2, _translate("Dialog", "Angle Section"))
        self.section_type_combobox.setItemText(3, _translate("Dialog", "Channel Section"))
        self.section_type_combobox.setItemText(4, _translate("Dialog", "Built-Up Section"))
        self.section_type_combobox.setItemText(5, _translate("Dialog", "Compound Section"))
        self.label_3.setText(_translate("Dialog", "Section Template:"))
        self.section_template_combobox.setItemText(0, _translate("Dialog", "-------Select Template-------"))
        self.label_4.setText(_translate("Dialog", "Section Designation:"))
        self.label_5.setText(_translate("Dialog", "Section Properties"))
        self.label_6.setText(_translate("Dialog", "Area:"))
        self.label_9.setText(_translate("Dialog", "Radius of Gyration:"))
        self.label_12.setText(_translate("Dialog", "Rzz:"))
        self.label_13.setText(_translate("Dialog", "Ryy:"))
        self.label_10.setText(_translate("Dialog", "Elastic Section Moduli:"))
        self.label_14.setText(_translate("Dialog", "Zzz:"))
        self.label_15.setText(_translate("Dialog", "Zyy:"))
        self.label_8.setText(_translate("Dialog", "Centroid:"))
        self.label_16.setText(_translate("Dialog", "Cy:"))
        self.label_17.setText(_translate("Dialog", "Cz:"))
        self.label_7.setText(_translate("Dialog", "Moment of Inertia:"))
        self.MI_label_1.setText(_translate("Dialog", "Izz:"))
        self.MI_label_2.setText(_translate("Dialog", "Iyy:"))
        self.MI_label_3.setText(_translate("Dialog", "Ixy:"))
        self.MI_label_4.setText(_translate("Dialog", "𝛼:"))
        self.MI_label_5.setText(_translate("Dialog", "Iu:"))
        self.MI_label_6.setText(_translate("Dialog", "Iv:"))
        self.label_11.setText(_translate("Dialog", "Plastic Section Moduli:"))
        self.PSM_label_1.setText(_translate("Dialog", "Zpy:"))
        self.PSM_label_2.setText(_translate("Dialog", "Zpz:"))
        self.PSM_label_3.setText(_translate("Dialog", "Czp:"))
        self.saveBtn.setText(_translate("Dialog", "Save"))
        self.exportBtn.setText(_translate("Dialog", "Export"))



