# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_OsdagMainPage.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from .toggle_button import Switch

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1466, 857)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ResourceFiles/images/Osdag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget::showMaximised()")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setAutoFillBackground(False)
        #self.frame.setStyleSheet("background-color: #abc250;")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(4)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(40, 40, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.comboBox_help = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_help.sizePolicy().hasHeightForWidth())
        self.comboBox_help.setSizePolicy(sizePolicy)
        self.comboBox_help.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox_help.setAutoFillBackground(False)
        self.comboBox_help.setFrame(True)
        self.comboBox_help.setObjectName("comboBox_help")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.comboBox_help.addItem("")
        self.gridLayout.addWidget(self.comboBox_help, 1, 0)
        layout = QtWidgets.QHBoxLayout()
        self.lbl = QtWidgets.QLabel(self.centralwidget)
        # self.gridLayout.setHorizontalSpacing(20)
        self.lbl.setText('Dark Mode  ')
        layout.addWidget(self.lbl)
        self.switch = Switch(self.centralwidget, thumb_radius=8, track_radius=6)
        layout.addWidget(self.switch)
        self.gridLayout.addLayout(layout,1,1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.lbl.setSizePolicy(sizePolicy)
        self.switch.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.myStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myStackedWidget.sizePolicy().hasHeightForWidth())
        self.myStackedWidget.setSizePolicy(sizePolicy)
        self.myStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.myStackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.myStackedWidget.setObjectName("myStackedWidget")
        self.Osdagpage = QtWidgets.QWidget()
        self.Osdagpage.setObjectName("Osdagpage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Osdagpage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_OsdagHeader = QtWidgets.QLabel(self.Osdagpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_OsdagHeader.sizePolicy().hasHeightForWidth())
        #self.lbl_OsdagHeader.setSizePolicy(sizePolicy)
        #self.lbl_OsdagHeader.setMinimumSize(QtCore.QSize(0, 0))
        #self.lbl_OsdagHeader.setMaximumSize(QtCore.QSize(1200, 300))
        #self.lbl_OsdagHeader.setText("")
        self.lbl_OsdagHeader.setPixmap(QtGui.QPixmap("ResourceFiles/images/Osdag_header.png"))
        #self.lbl_OsdagHeader.setScaledContents(True)
        self.lbl_OsdagHeader.setAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignTop)
        self.lbl_OsdagHeader.setWordWrap(False)
        self.lbl_OsdagHeader.setObjectName("lbl_OsdagHeader")
        self.gridLayout_2.addWidget(self.lbl_OsdagHeader, 2, 0, 2, 4)

        self.lbl_fosseelogo = QtWidgets.QLabel(self.Osdagpage)
        self.lbl_fosseelogo.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_fosseelogo.setMaximumSize(QtCore.QSize(250, 92))
        self.lbl_fosseelogo.setText("")
        self.lbl_fosseelogo.setPixmap(QtGui.QPixmap(":/newPrefix/images/Fossee_logo.png"))
        #self.lbl_fosseelogo.setScaledContents(True)
        self.lbl_fosseelogo.setObjectName("lbl_fosseelogo")
        self.gridLayout_2.addWidget(self.lbl_fosseelogo, 3, 3, 1, 1)
        self.lbl_iitblogo = QtWidgets.QLabel(self.Osdagpage)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.lbl_iitblogo.sizePolicy().hasHeightForWidth())
        # self.lbl_iitblogo.setSizePolicy(sizePolicy)
        self.lbl_iitblogo.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_iitblogo.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_iitblogo.setText("")
        self.lbl_iitblogo.setPixmap(QtGui.QPixmap(":/newPrefix/images/logoiitb.png"))
        #self.lbl_iitblogo.setScaledContents(True)
        self.lbl_iitblogo.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_iitblogo.setObjectName("lbl_iitblogo")
        self.gridLayout_2.addWidget(self.lbl_iitblogo, 3, 0, 1, 1)
        self.myStackedWidget.addWidget(self.Osdagpage)
        self.gridLayout.addWidget(self.myStackedWidget, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1466, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_help.setCurrentIndex(0)
        self.myStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Osdag"))
        self.comboBox_help.setItemText(0, _translate("MainWindow", "Help"))
        self.comboBox_help.setItemText(1, _translate("MainWindow", "Video Tutorials"))
        self.comboBox_help.setItemText(2, _translate("MainWindow", "Design Examples"))
        self.comboBox_help.setItemText(3, _translate("MainWindow", "Ask Us a Question"))
        self.comboBox_help.setItemText(4, _translate("MainWindow", "Check for Update"))
        self.comboBox_help.setItemText(5, _translate("MainWindow", "About Osdag"))
import gui.osdagMainPageIcons_rc
