# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_section_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SectionParameters(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(319, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 300))
        Dialog.setMaximumSize(QtCore.QSize(100000, 300))
        Dialog.setModal(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameterLabel_1 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_1.setFont(font)
        self.parameterLabel_1.setObjectName("parameterLabel_1")
        self.verticalLayout.addWidget(self.parameterLabel_1)
        self.parameterLabel_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_2.setFont(font)
        self.parameterLabel_2.setObjectName("parameterLabel_2")
        self.verticalLayout.addWidget(self.parameterLabel_2)
        self.parameterLabel_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_3.setFont(font)
        self.parameterLabel_3.setObjectName("parameterLabel_3")
        self.verticalLayout.addWidget(self.parameterLabel_3)
        self.parameterLabel_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_4.setFont(font)
        self.parameterLabel_4.setObjectName("parameterLabel_4")
        self.verticalLayout.addWidget(self.parameterLabel_4)
        self.parameterLabel_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_5.setFont(font)
        self.parameterLabel_5.setObjectName("parameterLabel_5")
        self.verticalLayout.addWidget(self.parameterLabel_5)
        self.parameterLabel_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_6.setFont(font)
        self.parameterLabel_6.setObjectName("parameterLabel_6")
        self.verticalLayout.addWidget(self.parameterLabel_6)
        self.parameterLabel_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterLabel_7.setFont(font)
        self.parameterLabel_7.setObjectName("parameterLabel_7")
        self.verticalLayout.addWidget(self.parameterLabel_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parameterText_1 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_1.sizePolicy().hasHeightForWidth())
        self.parameterText_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_1.setFont(font)
        self.parameterText_1.setObjectName("parameterText_1")
        self.verticalLayout_2.addWidget(self.parameterText_1)
        self.parameterText_2 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_2.sizePolicy().hasHeightForWidth())
        self.parameterText_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_2.setFont(font)
        self.parameterText_2.setObjectName("parameterText_2")
        self.verticalLayout_2.addWidget(self.parameterText_2)
        self.parameterText_3 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_3.sizePolicy().hasHeightForWidth())
        self.parameterText_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_3.setFont(font)
        self.parameterText_3.setObjectName("parameterText_3")
        self.verticalLayout_2.addWidget(self.parameterText_3)
        self.parameterText_4 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_4.sizePolicy().hasHeightForWidth())
        self.parameterText_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_4.setFont(font)
        self.parameterText_4.setObjectName("parameterText_4")
        self.verticalLayout_2.addWidget(self.parameterText_4)
        self.parameterText_5 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_5.sizePolicy().hasHeightForWidth())
        self.parameterText_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_5.setFont(font)
        self.parameterText_5.setObjectName("parameterText_5")
        self.verticalLayout_2.addWidget(self.parameterText_5)
        self.parameterText_6 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_6.sizePolicy().hasHeightForWidth())
        self.parameterText_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_6.setFont(font)
        self.parameterText_6.setObjectName("parameterText_6")
        self.verticalLayout_2.addWidget(self.parameterText_6)
        self.parameterText_7 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterText_7.sizePolicy().hasHeightForWidth())
        self.parameterText_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parameterText_7.setFont(font)
        self.parameterText_7.setObjectName("parameterText_7")
        self.verticalLayout_2.addWidget(self.parameterText_7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.okBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_2.addWidget(self.okBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Section Parameters"))
        self.parameterLabel_1.setText(_translate("Dialog", "I-Section Type:"))
        self.parameterLabel_2.setText(_translate("Dialog", "Channel Type:"))
        self.parameterLabel_3.setText(_translate("Dialog", "Spacing (s):"))
        self.parameterLabel_4.setText(_translate("Dialog", "Spacing (s*):"))
        self.parameterLabel_5.setText(_translate("Dialog", "Alpha (𝛼):"))
        self.parameterLabel_6.setText(_translate("Dialog", "Length (l):"))
        self.parameterLabel_7.setText(_translate("Dialog", "Thickness (t):"))
        self.okBtn.setText(_translate("Dialog", "OK"))
