PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "BOLT" (
	"DIAMETER"	REAL(10,2)
);
INSERT INTO BOLT VALUES(1.18);
INSERT INTO BOLT VALUES(8.18);
INSERT INTO BOLT VALUES(10.18);
INSERT INTO BOLT VALUES(12.18);
INSERT INTO BOLT VALUES(14.18);
INSERT INTO BOLT VALUES(16.18);
COMMIT;
