PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "BOLT" (
	"DIAMETER"	INTEGER
);
INSERT INTO BOLT VALUES(6);
INSERT INTO BOLT VALUES(8);
INSERT INTO BOLT VALUES(10);
INSERT INTO BOLT VALUES(12);
INSERT INTO BOLT VALUES(16);
INSERT INTO BOLT VALUES(20);
INSERT INTO BOLT VALUES(24);
INSERT INTO BOLT VALUES(28);
INSERT INTO BOLT VALUES(30);
INSERT INTO BOLT VALUES(32);
INSERT INTO BOLT VALUES(36);
COMMIT;
