# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pitch.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pitch(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(334, 209)
        Dialog.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 257, 313))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_mem4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem4.setFont(font)
        self.lbl_mem4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem4.setObjectName("lbl_mem4")
        self.gridLayout_2.addWidget(self.lbl_mem4, 6, 0, 3, 1)
        self.lbl_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_4.setFont(font)
        self.lbl_4.setText("")
        self.lbl_4.setObjectName("lbl_4")
        self.gridLayout_2.addWidget(self.lbl_4, 8, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 8, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 10, 6, 1, 1)
        self.lbl_mem5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem5.setFont(font)
        self.lbl_mem5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem5.setObjectName("lbl_mem5")
        self.gridLayout_2.addWidget(self.lbl_mem5, 9, 0, 2, 1)
        self.lineEdit_pitch5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch5.setFont(font)
        self.lineEdit_pitch5.setReadOnly(True)
        self.lineEdit_pitch5.setObjectName("lineEdit_pitch5")
        self.gridLayout_2.addWidget(self.lineEdit_pitch5, 10, 5, 1, 1)
        self.lbl_mem6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem6.setFont(font)
        self.lbl_mem6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem6.setObjectName("lbl_mem6")
        self.gridLayout_2.addWidget(self.lbl_mem6, 11, 0, 2, 1)
        self.lineEdit_pitch6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch6.setFont(font)
        self.lineEdit_pitch6.setReadOnly(True)
        self.lineEdit_pitch6.setObjectName("lineEdit_pitch6")
        self.gridLayout_2.addWidget(self.lineEdit_pitch6, 12, 5, 2, 1)
        self.lbl_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_3.setFont(font)
        self.lbl_3.setText("")
        self.lbl_3.setObjectName("lbl_3")
        self.gridLayout_2.addWidget(self.lbl_3, 5, 2, 1, 1)
        self.lineEdit_pitch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch3.setFont(font)
        self.lineEdit_pitch3.setReadOnly(True)
        self.lineEdit_pitch3.setObjectName("lineEdit_pitch3")
        self.gridLayout_2.addWidget(self.lineEdit_pitch3, 5, 5, 1, 1)
        self.lbl_mem7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem7.setFont(font)
        self.lbl_mem7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem7.setObjectName("lbl_mem7")
        self.gridLayout_2.addWidget(self.lbl_mem7, 13, 0, 2, 1)
        self.lineEdit_pitch7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch7.setFont(font)
        self.lineEdit_pitch7.setReadOnly(True)
        self.lineEdit_pitch7.setObjectName("lineEdit_pitch7")
        self.gridLayout_2.addWidget(self.lineEdit_pitch7, 14, 5, 2, 1)
        self.lbl_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_6.setFont(font)
        self.lbl_6.setText("")
        self.lbl_6.setObjectName("lbl_6")
        self.gridLayout_2.addWidget(self.lbl_6, 12, 3, 1, 1)
        self.lbl_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_7.setFont(font)
        self.lbl_7.setText("")
        self.lbl_7.setObjectName("lbl_7")
        self.gridLayout_2.addWidget(self.lbl_7, 15, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 4, 16, 1)
        self.lbl_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_1.setFont(font)
        self.lbl_1.setText("")
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout_2.addWidget(self.lbl_1, 1, 2, 1, 1)
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch.setFont(font)
        self.lineEdit_pitch.setReadOnly(True)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout_2.addWidget(self.lineEdit_pitch, 1, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 16, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_2.setFont(font)
        self.lbl_2.setText("")
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_2.addWidget(self.lbl_2, 2, 2, 2, 1)
        self.lbl_mem2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2.setFont(font)
        self.lbl_mem2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2.setObjectName("lbl_mem2")
        self.gridLayout_2.addWidget(self.lbl_mem2, 2, 0, 2, 1)
        self.lineEdit_pitch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch2.setFont(font)
        self.lineEdit_pitch2.setReadOnly(True)
        self.lineEdit_pitch2.setObjectName("lineEdit_pitch2")
        self.gridLayout_2.addWidget(self.lineEdit_pitch2, 3, 5, 1, 1)
        self.lbl_mem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem.setFont(font)
        self.lbl_mem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem.setObjectName("lbl_mem")
        self.gridLayout_2.addWidget(self.lbl_mem, 1, 0, 1, 1)
        self.lbl_mem3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_mem3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem3.setFont(font)
        self.lbl_mem3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem3.setObjectName("lbl_mem3")
        self.gridLayout_2.addWidget(self.lbl_mem3, 4, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 2)
        self.lineEdit_pitch4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch4.setFont(font)
        self.lineEdit_pitch4.setReadOnly(True)
        self.lineEdit_pitch4.setObjectName("lineEdit_pitch4")
        self.gridLayout_2.addWidget(self.lineEdit_pitch4, 7, 5, 2, 1)
        self.lbl_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_5.setFont(font)
        self.lbl_5.setText("")
        self.lbl_5.setObjectName("lbl_5")
        self.gridLayout_2.addWidget(self.lbl_5, 10, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 12, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 14, 6, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.lbl_image = QtWidgets.QLabel(Dialog)
        self.lbl_image.setObjectName("lbl_image")
        self.gridLayout.addWidget(self.lbl_image, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pitch Details"))
        self.label.setText(_translate("Dialog", "Sr. No."))
        self.lbl_mem4.setText(_translate("Dialog", "4"))
        self.lbl_mem5.setText(_translate("Dialog", "5"))
        self.lbl_mem6.setText(_translate("Dialog", "6"))
        self.lbl_mem7.setText(_translate("Dialog", "7"))
        self.label_5.setText(_translate("Dialog", "Pitch (mm)"))
        self.lbl_mem2.setText(_translate("Dialog", "2"))
        self.lbl_mem.setText(_translate("Dialog", "1"))
        self.lbl_mem3.setText(_translate("Dialog", "3"))
        self.label_2.setText(_translate("Dialog", "Designation"))
        self.lbl_image.setText(_translate("Dialog", "TextLabel"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Pitch()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

