# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pitch.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pitch(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 400)
        Dialog.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 543, 380))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 241, 341))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../ResourceFiles/images/cleatAngle.png"))
        self.label_3.setObjectName("label_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 20, 271, 251))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 269, 249))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 36, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 67, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(180, 10, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_pitch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch2.setGeometry(QtCore.QRect(150, 70, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch2.setFont(font)
        self.lineEdit_pitch2.setReadOnly(True)
        self.lineEdit_pitch2.setObjectName("lineEdit_pitch2")
        self.lineEdit_pitch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch3.setGeometry(QtCore.QRect(150, 100, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch3.setFont(font)
        self.lineEdit_pitch3.setReadOnly(True)
        self.lineEdit_pitch3.setObjectName("lineEdit_pitch3")
        self.lineEdit_pitch4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch4.setGeometry(QtCore.QRect(150, 130, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch4.setFont(font)
        self.lineEdit_pitch4.setReadOnly(True)
        self.lineEdit_pitch4.setObjectName("lineEdit_pitch4")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(150, 40, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch.setFont(font)
        self.lineEdit_pitch.setReadOnly(True)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.lineEdit_pitch5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch5.setGeometry(QtCore.QRect(150, 160, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch5.setFont(font)
        self.lineEdit_pitch5.setReadOnly(True)
        self.lineEdit_pitch5.setObjectName("lineEdit_pitch5")
        self.lineEdit_pitch6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch6.setGeometry(QtCore.QRect(150, 190, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch6.setFont(font)
        self.lineEdit_pitch6.setReadOnly(True)
        self.lineEdit_pitch6.setObjectName("lineEdit_pitch6")
        self.lbl_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_1.setGeometry(QtCore.QRect(60, 40, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_1.setFont(font)
        self.lbl_1.setObjectName("lbl_1")
        self.lbl_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_2.setGeometry(QtCore.QRect(60, 70, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_2.setFont(font)
        self.lbl_2.setObjectName("lbl_2")
        self.lbl_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_3.setGeometry(QtCore.QRect(60, 100, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_3.setFont(font)
        self.lbl_3.setObjectName("lbl_3")
        self.lbl_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_4.setGeometry(QtCore.QRect(60, 130, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_4.setFont(font)
        self.lbl_4.setObjectName("lbl_4")
        self.lbl_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_5.setGeometry(QtCore.QRect(60, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_5.setFont(font)
        self.lbl_5.setObjectName("lbl_5")
        self.lbl_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_6.setGeometry(QtCore.QRect(60, 160, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_6.setFont(font)
        self.lbl_6.setObjectName("lbl_6")
        self.lbl_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_7.setGeometry(QtCore.QRect(60, 220, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_7.setFont(font)
        self.lbl_7.setObjectName("lbl_7")
        self.lbl_mem = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem.setGeometry(QtCore.QRect(20, 40, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem.setFont(font)
        self.lbl_mem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem.setObjectName("lbl_mem")
        self.lbl_mem2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem2.setGeometry(QtCore.QRect(20, 70, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2.setFont(font)
        self.lbl_mem2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2.setObjectName("lbl_mem2")
        self.lbl_mem3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem3.setEnabled(True)
        self.lbl_mem3.setGeometry(QtCore.QRect(20, 100, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem3.setFont(font)
        self.lbl_mem3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem3.setObjectName("lbl_mem3")
        self.lbl_mem4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem4.setGeometry(QtCore.QRect(20, 130, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem4.setFont(font)
        self.lbl_mem4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem4.setObjectName("lbl_mem4")
        self.lbl_mem5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem5.setGeometry(QtCore.QRect(20, 160, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem5.setFont(font)
        self.lbl_mem5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem5.setObjectName("lbl_mem5")
        self.lbl_mem6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem6.setGeometry(QtCore.QRect(20, 190, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem6.setFont(font)
        self.lbl_mem6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem6.setObjectName("lbl_mem6")
        self.lbl_mem7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mem7.setGeometry(QtCore.QRect(20, 220, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem7.setFont(font)
        self.lbl_mem7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem7.setObjectName("lbl_mem7")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(40, 3, 20, 241))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setGeometry(QtCore.QRect(130, 0, 20, 251))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.lineEdit_pitch7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_pitch7.setGeometry(QtCore.QRect(150, 220, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_pitch7.setFont(font)
        self.lineEdit_pitch7.setReadOnly(True)
        self.lineEdit_pitch7.setObjectName("lineEdit_pitch7")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pitch Details"))
        self.label.setText(_translate("Dialog", "Sr. No."))
        self.label_2.setText(_translate("Dialog", "Designation"))
        self.label_5.setText(_translate("Dialog", "Pitch (mm)"))
        self.lbl_1.setText(_translate("Dialog", "Pitch 12-20"))
        self.lbl_2.setText(_translate("Dialog", "er"))
        self.lbl_3.setText(_translate("Dialog", "ty"))
        self.lbl_4.setText(_translate("Dialog", "we"))
        self.lbl_5.setText(_translate("Dialog", "rt"))
        self.lbl_6.setText(_translate("Dialog", "yt"))
        self.lbl_7.setText(_translate("Dialog", "yt"))
        self.lbl_mem.setText(_translate("Dialog", "1"))
        self.lbl_mem2.setText(_translate("Dialog", "2"))
        self.lbl_mem3.setText(_translate("Dialog", "3"))
        self.lbl_mem4.setText(_translate("Dialog", "4"))
        self.lbl_mem5.setText(_translate("Dialog", "5"))
        self.lbl_mem6.setText(_translate("Dialog", "6"))
        self.lbl_mem7.setText(_translate("Dialog", "7"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Pitch()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

