# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DesignPreferences(object):
    def setupUi(self, DesignPreferences):
        DesignPreferences.setObjectName("DesignPreferences")
        DesignPreferences.resize(969, 633)
        self.gridLayout_5 = QtWidgets.QGridLayout(DesignPreferences)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_defaults = QtWidgets.QPushButton(DesignPreferences)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_defaults.setFont(font)
        self.btn_defaults.setObjectName("btn_defaults")
        self.gridLayout_2.addWidget(self.btn_defaults, 0, 1, 1, 1)
        self.btn_save = QtWidgets.QPushButton(DesignPreferences)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_2.addWidget(self.btn_save, 0, 2, 1, 1)
        self.btn_close = QtWidgets.QPushButton(DesignPreferences)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.gridLayout_2.addWidget(self.btn_close, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(DesignPreferences)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Column = QtWidgets.QWidget()
        self.tab_Column.setObjectName("tab_Column")
        self.label_31 = QtWidgets.QLabel(self.tab_Column)
        self.label_31.setGeometry(QtCore.QRect(330, 90, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_28 = QtWidgets.QLabel(self.tab_Column)
        self.label_28.setGeometry(QtCore.QRect(10, 231, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_43 = QtWidgets.QLabel(self.tab_Column)
        self.label_43.setGeometry(QtCore.QRect(330, 439, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_ElasticModPZ_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ElasticModPZ_Column.setGeometry(QtCore.QRect(540, 440, 111, 25))
        self.lineEdit_ElasticModPZ_Column.setObjectName("lineEdit_ElasticModPZ_Column")
        self.label_48 = QtWidgets.QLabel(self.tab_Column)
        self.label_48.setGeometry(QtCore.QRect(10, 261, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_53 = QtWidgets.QLabel(self.tab_Column)
        self.label_53.setGeometry(QtCore.QRect(330, 199, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.lineEdit_RogY_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_RogY_Column.setGeometry(QtCore.QRect(540, 350, 111, 25))
        self.lineEdit_RogY_Column.setObjectName("lineEdit_RogY_Column")
        self.line_7 = QtWidgets.QFrame(self.tab_Column)
        self.line_7.setGeometry(QtCore.QRect(650, 170, 31, 331))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_Add_Column = QtWidgets.QPushButton(self.tab_Column)
        self.pushButton_Add_Column.setGeometry(QtCore.QRect(180, 510, 89, 25))
        self.pushButton_Add_Column.setObjectName("pushButton_Add_Column")
        self.lineEdit_FlangeThickness_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_FlangeThickness_Column.setGeometry(QtCore.QRect(190, 261, 113, 25))
        self.lineEdit_FlangeThickness_Column.setObjectName("lineEdit_FlangeThickness_Column")
        self.label_41 = QtWidgets.QLabel(self.tab_Column)
        self.label_41.setGeometry(QtCore.QRect(340, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_30 = QtWidgets.QLabel(self.tab_Column)
        self.label_30.setGeometry(QtCore.QRect(10, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_YieldStrength_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_YieldStrength_Column.setGeometry(QtCore.QRect(200, 130, 101, 25))
        self.lineEdit_YieldStrength_Column.setObjectName("lineEdit_YieldStrength_Column")
        self.label_42 = QtWidgets.QLabel(self.tab_Column)
        self.label_42.setGeometry(QtCore.QRect(330, 379, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.lineEdit_Designation_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_Designation_Column.setGeometry(QtCore.QRect(90, 10, 241, 25))
        self.lineEdit_Designation_Column.setObjectName("lineEdit_Designation_Column")
        self.pushButton_Import_Column = QtWidgets.QPushButton(self.tab_Column)
        self.pushButton_Import_Column.setGeometry(QtCore.QRect(800, 510, 121, 25))
        self.pushButton_Import_Column.setObjectName("pushButton_Import_Column")

        self.label_37 = QtWidgets.QLabel(self.tab_Column)
        self.label_37.setGeometry(QtCore.QRect(330, 130, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_34 = QtWidgets.QLabel(self.tab_Column)
        self.label_34.setGeometry(QtCore.QRect(330, 259, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_44 = QtWidgets.QLabel(self.tab_Column)
        self.label_44.setGeometry(QtCore.QRect(330, 409, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_49 = QtWidgets.QLabel(self.tab_Column)
        self.label_49.setGeometry(QtCore.QRect(10, 291, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.lineEdit_Depth_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_Depth_Column.setGeometry(QtCore.QRect(190, 201, 113, 25))
        self.lineEdit_Depth_Column.setObjectName("lineEdit_Depth_Column")
        self.label_51 = QtWidgets.QLabel(self.tab_Column)
        self.label_51.setGeometry(QtCore.QRect(330, 319, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_29 = QtWidgets.QLabel(self.tab_Column)
        self.label_29.setGeometry(QtCore.QRect(330, 289, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.pushButton_Clear_Column = QtWidgets.QPushButton(self.tab_Column)
        self.pushButton_Clear_Column.setGeometry(QtCore.QRect(40, 510, 89, 25))
        self.pushButton_Clear_Column.setObjectName("pushButton_Clear_Column")
        self.lineEdit_ModElasticity_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ModElasticity_Column.setGeometry(QtCore.QRect(550, 90, 101, 25))
        self.lineEdit_ModElasticity_Column.setObjectName("lineEdit_ModElasticity_Column")
        self.pushButton_Download_Column = QtWidgets.QPushButton(self.tab_Column)
        self.pushButton_Download_Column.setGeometry(QtCore.QRect(590, 510, 171, 25))
        self.pushButton_Download_Column.setObjectName("pushButton_Download_Column")
        self.lineEdit_FlangeWidth_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_FlangeWidth_Column.setGeometry(QtCore.QRect(190, 231, 113, 25))
        self.lineEdit_FlangeWidth_Column.setObjectName("lineEdit_FlangeWidth_Column")
        self.lineEdit_MomentOfAreaY_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_MomentOfAreaY_Column.setGeometry(QtCore.QRect(540, 290, 111, 25))
        self.lineEdit_MomentOfAreaY_Column.setObjectName("lineEdit_MomentOfAreaY_Column")
        self.lineEdit_ToeRadius_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ToeRadius_Column.setGeometry(QtCore.QRect(190, 381, 113, 25))
        self.lineEdit_ToeRadius_Column.setObjectName("lineEdit_ToeRadius_Column")
        self.lineEdit_RogZ_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_RogZ_Column.setGeometry(QtCore.QRect(540, 320, 111, 25))
        self.lineEdit_RogZ_Column.setObjectName("lineEdit_RogZ_Column")
        self.label_47 = QtWidgets.QLabel(self.tab_Column)
        self.label_47.setGeometry(QtCore.QRect(10, 321, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.lineEdit_WeBThickness_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_WeBThickness_Column.setGeometry(QtCore.QRect(190, 291, 113, 25))
        self.lineEdit_WeBThickness_Column.setObjectName("lineEdit_WeBThickness_Column")
        self.lineEdit_ElasticModPY_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ElasticModPY_Column.setGeometry(QtCore.QRect(540, 470, 111, 25))
        self.lineEdit_ElasticModPY_Column.setObjectName("lineEdit_ElasticModPY_Column")
        self.label_50 = QtWidgets.QLabel(self.tab_Column)
        self.label_50.setGeometry(QtCore.QRect(10, 351, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_35 = QtWidgets.QLabel(self.tab_Column)
        self.label_35.setGeometry(QtCore.QRect(650, 11, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_52 = QtWidgets.QLabel(self.tab_Column)
        self.label_52.setGeometry(QtCore.QRect(330, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.lineEdit_UltimateStrength_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_UltimateStrength_Column.setGeometry(QtCore.QRect(200, 90, 101, 25))
        self.lineEdit_UltimateStrength_Column.setObjectName("lineEdit_UltimateStrength_Column")
        self.lineEdit_FlangeSlope_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_FlangeSlope_Column.setGeometry(QtCore.QRect(190, 321, 113, 25))
        self.lineEdit_FlangeSlope_Column.setObjectName("lineEdit_FlangeSlope_Column")
        self.label_33 = QtWidgets.QLabel(self.tab_Column)
        self.label_33.setGeometry(QtCore.QRect(330, 349, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_ElasticModZ_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ElasticModZ_Column.setGeometry(QtCore.QRect(540, 380, 111, 25))
        self.lineEdit_ElasticModZ_Column.setObjectName("lineEdit_ElasticModZ_Column")
        self.label_45 = QtWidgets.QLabel(self.tab_Column)
        self.label_45.setGeometry(QtCore.QRect(10, 161, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_36 = QtWidgets.QLabel(self.tab_Column)
        self.label_36.setGeometry(QtCore.QRect(10, 381, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_46 = QtWidgets.QLabel(self.tab_Column)
        self.label_46.setGeometry(QtCore.QRect(10, 90, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.lineEdit_MomentOfAreaZ_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_MomentOfAreaZ_Column.setGeometry(QtCore.QRect(540, 260, 111, 25))
        self.lineEdit_MomentOfAreaZ_Column.setObjectName("lineEdit_MomentOfAreaZ_Column")
        self.label_54 = QtWidgets.QLabel(self.tab_Column)
        self.label_54.setGeometry(QtCore.QRect(10, 201, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.lineEdit_ElasticModY_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ElasticModY_Column.setGeometry(QtCore.QRect(540, 410, 111, 25))
        self.lineEdit_ElasticModY_Column.setObjectName("lineEdit_ElasticModY_Column")
        self.lineEdit_Source_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_Source_Column.setGeometry(QtCore.QRect(700, 10, 221, 25))
        self.lineEdit_Source_Column.setObjectName("lineEdit_Source_Column")
        self.label_32 = QtWidgets.QLabel(self.tab_Column)
        self.label_32.setGeometry(QtCore.QRect(10, 51, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_ModulusOfRigidity_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ModulusOfRigidity_Column.setGeometry(QtCore.QRect(550, 130, 101, 25))
        self.lineEdit_ModulusOfRigidity_Column.setObjectName("lineEdit_ModulusOfRigidity_Column")
        self.label_55 = QtWidgets.QLabel(self.tab_Column)
        self.label_55.setGeometry(QtCore.QRect(10, 130, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.line_9 = QtWidgets.QFrame(self.tab_Column)
        self.line_9.setGeometry(QtCore.QRect(300, 171, 31, 331))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lineEdit_SectionalArea_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_SectionalArea_Column.setGeometry(QtCore.QRect(540, 230, 111, 25))
        self.lineEdit_SectionalArea_Column.setObjectName("lineEdit_SectionalArea_Column")
        self.label_56 = QtWidgets.QLabel(self.tab_Column)
        self.label_56.setGeometry(QtCore.QRect(330, 469, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.line_10 = QtWidgets.QFrame(self.tab_Column)
        self.line_10.setGeometry(QtCore.QRect(-10, 491, 971, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.lineEdit_RootRadius_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_RootRadius_Column.setGeometry(QtCore.QRect(190, 351, 113, 25))
        self.lineEdit_RootRadius_Column.setObjectName("lineEdit_RootRadius_Column")
        self.label_57 = QtWidgets.QLabel(self.tab_Column)
        self.label_57.setGeometry(QtCore.QRect(330, 229, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.lineEdit_Mass_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_Mass_Column.setGeometry(QtCore.QRect(540, 199, 111, 25))
        self.lineEdit_Mass_Column.setObjectName("lineEdit_Mass_Column")
        self.comboBox_Column = QtWidgets.QComboBox(self.tab_Column)
        self.comboBox_Column.setGeometry(QtCore.QRect(380, 10, 261, 25))
        self.comboBox_Column.setObjectName("comboBox_Column")
        self.comboBox_Column.addItem("")
        self.comboBox_Column.addItem("")
        self.lineEdit_PoissionsRatio_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_PoissionsRatio_Column.setGeometry(QtCore.QRect(810, 90, 111, 25))
        self.lineEdit_PoissionsRatio_Column.setObjectName("lineEdit_PoissionsRatio_Column")
        self.label_85 = QtWidgets.QLabel(self.tab_Column)
        self.label_85.setGeometry(QtCore.QRect(670, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.lineEdit_ThermalExpansion_Column = QtWidgets.QLineEdit(self.tab_Column)
        self.lineEdit_ThermalExpansion_Column.setGeometry(QtCore.QRect(810, 130, 111, 25))
        self.lineEdit_ThermalExpansion_Column.setObjectName("lineEdit_ThermalExpansion_Column")
        self.label_86 = QtWidgets.QLabel(self.tab_Column)
        self.label_86.setGeometry(QtCore.QRect(670, 120, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.label_13 = QtWidgets.QLabel(self.tab_Column)
        self.label_13.setGeometry(QtCore.QRect(700, 160, 241, 341))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/images/user_section1.png"))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_Column, "")
        self.tab_Beam = QtWidgets.QWidget()
        self.tab_Beam.setObjectName("tab_Beam")
        self.label_58 = QtWidgets.QLabel(self.tab_Beam)
        self.label_58.setGeometry(QtCore.QRect(330, 90, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_Beam)
        self.label_59.setGeometry(QtCore.QRect(10, 231, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.lineEdit_ElasticModPZ_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ElasticModPZ_Beam.setGeometry(QtCore.QRect(540, 440, 111, 25))
        self.lineEdit_ElasticModPZ_Beam.setObjectName("lineEdit_ElasticModPZ_Beam")
        self.label_61 = QtWidgets.QLabel(self.tab_Beam)
        self.label_61.setGeometry(QtCore.QRect(10, 261, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_Beam)
        self.label_62.setGeometry(QtCore.QRect(330, 199, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.lineEdit_RogY_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_RogY_Beam.setGeometry(QtCore.QRect(540, 350, 111, 25))
        self.lineEdit_RogY_Beam.setObjectName("lineEdit_RogY_Beam")
        self.line_12 = QtWidgets.QFrame(self.tab_Beam)
        self.line_12.setGeometry(QtCore.QRect(650, 170, 31, 331))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.pushButton_Add_Beam = QtWidgets.QPushButton(self.tab_Beam)
        self.pushButton_Add_Beam.setGeometry(QtCore.QRect(180, 510, 89, 25))
        self.pushButton_Add_Beam.setObjectName("pushButton_Add_Beam")
        self.lineEdit_FlangeThickness_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_FlangeThickness_Beam.setGeometry(QtCore.QRect(190, 261, 113, 25))
        self.lineEdit_FlangeThickness_Beam.setObjectName("lineEdit_FlangeThickness_Beam")
        self.label_63 = QtWidgets.QLabel(self.tab_Beam)
        self.label_63.setGeometry(QtCore.QRect(340, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_Beam)
        self.label_64.setGeometry(QtCore.QRect(10, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.lineEdit_YieldStrength_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_YieldStrength_Beam.setGeometry(QtCore.QRect(200, 130, 101, 25))
        self.lineEdit_YieldStrength_Beam.setObjectName("lineEdit_YieldStrength_Beam")
        self.lineEdit_Designation_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_Designation_Beam.setGeometry(QtCore.QRect(90, 10, 241, 25))
        self.lineEdit_Designation_Beam.setObjectName("lineEdit_Designation_Beam")
        self.pushButton_Import_Beam = QtWidgets.QPushButton(self.tab_Beam)
        self.pushButton_Import_Beam.setGeometry(QtCore.QRect(800, 510, 121, 25))
        self.pushButton_Import_Beam.setObjectName("pushButton_Import_Beam")
        #self.pushButton_Import_Beam.setEnabled(True)
        self.label_66 = QtWidgets.QLabel(self.tab_Beam)
        self.label_66.setGeometry(QtCore.QRect(330, 130, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.label_69 = QtWidgets.QLabel(self.tab_Beam)
        self.label_69.setGeometry(QtCore.QRect(10, 291, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.lineEdit_Depth_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_Depth_Beam.setGeometry(QtCore.QRect(190, 201, 113, 25))
        self.lineEdit_Depth_Beam.setObjectName("lineEdit_Depth_Beam")
        self.pushButton_Clear_Beam = QtWidgets.QPushButton(self.tab_Beam)
        self.pushButton_Clear_Beam.setGeometry(QtCore.QRect(40, 510, 89, 25))
        self.pushButton_Clear_Beam.setObjectName("pushButton_Clear_Beam")
        self.lineEdit_ModElasticity_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ModElasticity_Beam.setGeometry(QtCore.QRect(550, 90, 101, 25))
        self.lineEdit_ModElasticity_Beam.setObjectName("lineEdit_ModElasticity_Beam")
        self.pushButton_Download_Beam = QtWidgets.QPushButton(self.tab_Beam)
        self.pushButton_Download_Beam.setGeometry(QtCore.QRect(590, 510, 171, 25))
        self.pushButton_Download_Beam.setObjectName("pushButton_Download_Beam")
        self.lineEdit_FlangeWidth_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_FlangeWidth_Beam.setGeometry(QtCore.QRect(190, 231, 113, 25))
        self.lineEdit_FlangeWidth_Beam.setObjectName("lineEdit_FlangeWidth_Beam")
        self.lineEdit_MomentOfAreaY_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_MomentOfAreaY_Beam.setGeometry(QtCore.QRect(540, 290, 111, 25))
        self.lineEdit_MomentOfAreaY_Beam.setObjectName("lineEdit_MomentOfAreaY_Beam")
        self.lineEdit_ToeRadius_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ToeRadius_Beam.setGeometry(QtCore.QRect(190, 381, 113, 25))
        self.lineEdit_ToeRadius_Beam.setObjectName("lineEdit_ToeRadius_Beam")
        self.lineEdit_RogZ_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_RogZ_Beam.setGeometry(QtCore.QRect(540, 320, 111, 25))
        self.lineEdit_RogZ_Beam.setObjectName("lineEdit_RogZ_Beam")
        self.lineEdit_WeBThickness_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_WeBThickness_Beam.setGeometry(QtCore.QRect(190, 291, 113, 25))
        self.lineEdit_WeBThickness_Beam.setObjectName("lineEdit_WeBThickness_Beam")
        self.lineEdit_ElasticModPY_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ElasticModPY_Beam.setGeometry(QtCore.QRect(540, 470, 111, 25))
        self.lineEdit_ElasticModPY_Beam.setObjectName("lineEdit_ElasticModPY_Beam")
        self.label_73 = QtWidgets.QLabel(self.tab_Beam)
        self.label_73.setGeometry(QtCore.QRect(10, 351, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_Beam)
        self.label_74.setGeometry(QtCore.QRect(650, 11, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_Beam)
        self.label_75.setGeometry(QtCore.QRect(330, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.lineEdit_UltimateStrength_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_UltimateStrength_Beam.setGeometry(QtCore.QRect(200, 90, 101, 25))
        self.lineEdit_UltimateStrength_Beam.setObjectName("lineEdit_UltimateStrength_Beam")
        self.lineEdit_FlangeSlope_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_FlangeSlope_Beam.setGeometry(QtCore.QRect(190, 321, 113, 25))
        self.lineEdit_FlangeSlope_Beam.setObjectName("lineEdit_FlangeSlope_Beam")
        self.lineEdit_ElasticModZ_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ElasticModZ_Beam.setGeometry(QtCore.QRect(540, 380, 111, 25))
        self.lineEdit_ElasticModZ_Beam.setObjectName("lineEdit_ElasticModZ_Beam")
        self.label_77 = QtWidgets.QLabel(self.tab_Beam)
        self.label_77.setGeometry(QtCore.QRect(10, 161, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_Beam)
        self.label_78.setGeometry(QtCore.QRect(10, 381, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.tab_Beam)
        self.label_79.setGeometry(QtCore.QRect(10, 90, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.lineEdit_MomentOfAreaZ_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_MomentOfAreaZ_Beam.setGeometry(QtCore.QRect(540, 260, 111, 25))
        self.lineEdit_MomentOfAreaZ_Beam.setObjectName("lineEdit_MomentOfAreaZ_Beam")
        self.label_80 = QtWidgets.QLabel(self.tab_Beam)
        self.label_80.setGeometry(QtCore.QRect(10, 201, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.lineEdit_ElasticModY_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ElasticModY_Beam.setGeometry(QtCore.QRect(540, 410, 111, 25))
        self.lineEdit_ElasticModY_Beam.setObjectName("lineEdit_ElasticModY_Beam")
        self.lineEdit_Source_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_Source_Beam.setGeometry(QtCore.QRect(700, 10, 221, 25))
        self.lineEdit_Source_Beam.setObjectName("lineEdit_Source_Beam")
        self.label_81 = QtWidgets.QLabel(self.tab_Beam)
        self.label_81.setGeometry(QtCore.QRect(10, 51, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.lineEdit_ModulusOfRigidity_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ModulusOfRigidity_Beam.setGeometry(QtCore.QRect(550, 130, 101, 25))
        self.lineEdit_ModulusOfRigidity_Beam.setObjectName("lineEdit_ModulusOfRigidity_Beam")
        self.label_82 = QtWidgets.QLabel(self.tab_Beam)
        self.label_82.setGeometry(QtCore.QRect(10, 130, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.line_13 = QtWidgets.QFrame(self.tab_Beam)
        self.line_13.setGeometry(QtCore.QRect(300, 171, 31, 331))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.lineEdit_SectionalArea_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_SectionalArea_Beam.setGeometry(QtCore.QRect(540, 230, 111, 25))
        self.lineEdit_SectionalArea_Beam.setObjectName("lineEdit_SectionalArea_Beam")
        self.line_14 = QtWidgets.QFrame(self.tab_Beam)
        self.line_14.setGeometry(QtCore.QRect(-10, 491, 971, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.lineEdit_RootRadius_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_RootRadius_Beam.setGeometry(QtCore.QRect(190, 351, 113, 25))
        self.lineEdit_RootRadius_Beam.setObjectName("lineEdit_RootRadius_Beam")
        self.lineEdit_Mass_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_Mass_Beam.setGeometry(QtCore.QRect(540, 199, 111, 25))
        self.lineEdit_Mass_Beam.setObjectName("lineEdit_Mass_Beam")
        self.comboBox_Beam = QtWidgets.QComboBox(self.tab_Beam)
        self.comboBox_Beam.setGeometry(QtCore.QRect(380, 10, 261, 25))
        self.comboBox_Beam.setObjectName("comboBox_Beam")
        self.comboBox_Beam.addItem("")
        self.comboBox_Beam.addItem("")
        self.lineEdit_ThermalExpansion_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_ThermalExpansion_Beam.setGeometry(QtCore.QRect(810, 130, 111, 25))
        self.lineEdit_ThermalExpansion_Beam.setObjectName("lineEdit_ThermalExpansion_Beam")
        self.lineEdit_PoissonsRatio_Beam = QtWidgets.QLineEdit(self.tab_Beam)
        self.lineEdit_PoissonsRatio_Beam.setGeometry(QtCore.QRect(810, 90, 111, 25))
        self.lineEdit_PoissonsRatio_Beam.setObjectName("lineEdit_PoissonsRatio_Beam")
        self.label_88 = QtWidgets.QLabel(self.tab_Beam)
        self.label_88.setGeometry(QtCore.QRect(670, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.label_14 = QtWidgets.QLabel(self.tab_Beam)
        self.label_14.setGeometry(QtCore.QRect(700, 170, 241, 321))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/newPrefix/images/user_section1.png"))
        self.label_14.setObjectName("label_14")
        self.label_89 = QtWidgets.QLabel(self.tab_Beam)
        self.label_89.setGeometry(QtCore.QRect(670, 120, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.label_72 = QtWidgets.QLabel(self.tab_Beam)
        self.label_72.setGeometry(QtCore.QRect(10, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_145 = QtWidgets.QLabel(self.tab_Beam)
        self.label_145.setGeometry(QtCore.QRect(330, 410, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_145.setFont(font)
        self.label_145.setObjectName("label_145")
        self.label_146 = QtWidgets.QLabel(self.tab_Beam)
        self.label_146.setGeometry(QtCore.QRect(330, 260, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.label_147 = QtWidgets.QLabel(self.tab_Beam)
        self.label_147.setGeometry(QtCore.QRect(330, 230, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_147.setFont(font)
        self.label_147.setObjectName("label_147")
        self.label_148 = QtWidgets.QLabel(self.tab_Beam)
        self.label_148.setGeometry(QtCore.QRect(330, 470, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_148.setFont(font)
        self.label_148.setObjectName("label_148")
        self.label_149 = QtWidgets.QLabel(self.tab_Beam)
        self.label_149.setGeometry(QtCore.QRect(330, 290, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.label_150 = QtWidgets.QLabel(self.tab_Beam)
        self.label_150.setGeometry(QtCore.QRect(330, 320, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(self.tab_Beam)
        self.label_151.setGeometry(QtCore.QRect(330, 380, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.tab_Beam)
        self.label_152.setGeometry(QtCore.QRect(330, 440, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_152.setFont(font)
        self.label_152.setObjectName("label_152")
        self.label_153 = QtWidgets.QLabel(self.tab_Beam)
        self.label_153.setGeometry(QtCore.QRect(330, 350, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_153.setFont(font)
        self.label_153.setObjectName("label_153")
        self.tabWidget.addTab(self.tab_Beam, "")
        self.tab_Bolt = QtWidgets.QWidget()
        self.tab_Bolt.setObjectName("tab_Bolt")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_Bolt)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_9 = QtWidgets.QLabel(self.tab_Bolt)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_22.addWidget(self.label_9, 0, 2, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem2 = QtWidgets.QSpacerItem(17, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_21.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_note = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_note.setFont(font)
        self.label_note.setObjectName("label_note")
        self.gridLayout_20.addWidget(self.label_note, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 2, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 1, 0, 2, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_22.addWidget(self.label_11, 2, 2, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_Bolt)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_8.addWidget(self.line_4, 1, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_Bolt)
        self.textBrowser.setMinimumSize(QtCore.QSize(210, 320))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_19.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_19, 0, 1, 3, 2)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.line = QtWidgets.QFrame(self.tab_Bolt)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_15.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 1, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.combo_boltHoleType = QtWidgets.QComboBox(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.combo_boltHoleType.setFont(font)
        self.combo_boltHoleType.setFocusPolicy(QtCore.Qt.TabFocus)
        self.combo_boltHoleType.setObjectName("combo_boltHoleType")
        self.combo_boltHoleType.addItem("")
        self.combo_boltHoleType.addItem("")
        self.gridLayout.addWidget(self.combo_boltHoleType, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_Bolt)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.txt_boltFu = QtWidgets.QLineEdit(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.txt_boltFu.setFont(font)
        self.txt_boltFu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_boltFu.setReadOnly(False)
        self.txt_boltFu.setObjectName("txt_boltFu")
        self.gridLayout.addWidget(self.txt_boltFu, 2, 1, 1, 1)
        self.combo_boltType = QtWidgets.QComboBox(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.combo_boltType.setFont(font)
        self.combo_boltType.setObjectName("combo_boltType")
        self.combo_boltType.addItem("")
        self.combo_boltType.addItem("")
        self.gridLayout.addWidget(self.combo_boltType, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 1, 3, 1)
        self.gridLayout_14.addLayout(self.gridLayout_9, 0, 0, 1, 2)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(168, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 2, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(128, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem5, 0, 0, 1, 1)
        self.combo_slipfactor = QtWidgets.QComboBox(self.tab_Bolt)
        self.combo_slipfactor.setMinimumSize(QtCore.QSize(0, 0))
        self.combo_slipfactor.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.combo_slipfactor.setFont(font)
        self.combo_slipfactor.setObjectName("combo_slipfactor")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.combo_slipfactor.addItem("")
        self.gridLayout_11.addWidget(self.combo_slipfactor, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 1, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_Bolt)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_16.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Bolt, "")
        self.tab_Weld = QtWidgets.QWidget()
        self.tab_Weld.setObjectName("tab_Weld")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_Weld)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_16 = QtWidgets.QLabel(self.tab_Weld)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_17 = QtWidgets.QLabel(self.tab_Weld)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab_Weld)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 1, 0, 1, 1)
        self.textBrowser_weldDescription = QtWidgets.QTextBrowser(self.tab_Weld)
        self.textBrowser_weldDescription.setMinimumSize(QtCore.QSize(210, 320))
        self.textBrowser_weldDescription.setObjectName("textBrowser_weldDescription")
        self.gridLayout_7.addWidget(self.textBrowser_weldDescription, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 2, 4, 1)
        self.line_8 = QtWidgets.QFrame(self.tab_Weld)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_13.addWidget(self.line_8, 1, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tab_Weld)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.combo_weldType = QtWidgets.QComboBox(self.tab_Weld)
        self.combo_weldType.setObjectName("combo_weldType")
        self.combo_weldType.addItem("")
        self.combo_weldType.addItem("")
        self.gridLayout_3.addWidget(self.combo_weldType, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_Weld)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_Weld)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 0, 1, 1)
        self.txt_weldFu = QtWidgets.QLineEdit(self.tab_Weld)
        self.txt_weldFu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_weldFu.setObjectName("txt_weldFu")
        self.gridLayout_3.addWidget(self.txt_weldFu, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_Weld)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_3, 2, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 288, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Weld, "")
        self.tab_Detailing = QtWidgets.QWidget()
        self.tab_Detailing.setObjectName("tab_Detailing")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_Detailing)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_38 = QtWidgets.QLabel(self.tab_Detailing)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 0, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.tab_Detailing)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_6.addWidget(self.line_11, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_39 = QtWidgets.QLabel(self.tab_Detailing)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 0, 0, 1, 1)
        self.combo_detailingEdgeType = QtWidgets.QComboBox(self.tab_Detailing)
        self.combo_detailingEdgeType.setObjectName("combo_detailingEdgeType")
        self.combo_detailingEdgeType.addItem("")
        self.combo_detailingEdgeType.addItem("")
        self.gridLayout_4.addWidget(self.combo_detailingEdgeType, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_Detailing)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 1, 0, 1, 1)
        self.combo_detailing_memebers = QtWidgets.QComboBox(self.tab_Detailing)
        self.combo_detailing_memebers.setObjectName("combo_detailing_memebers")
        self.combo_detailing_memebers.addItem("")
        self.combo_detailing_memebers.addItem("")
        self.gridLayout_4.addWidget(self.combo_detailing_memebers, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.line_6 = QtWidgets.QFrame(self.tab_Detailing)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_10.addWidget(self.line_6, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_Detailing)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 1)
        self.textBrowser_detailingDescription = QtWidgets.QTextBrowser(self.tab_Detailing)
        self.textBrowser_detailingDescription.setMinimumSize(QtCore.QSize(210, 0))
        self.textBrowser_detailingDescription.setObjectName("textBrowser_detailingDescription")
        self.gridLayout_10.addWidget(self.textBrowser_detailingDescription, 2, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_10, 0, 1, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 255, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Detailing, "")
        self.tab_Design = QtWidgets.QWidget()
        self.tab_Design.setObjectName("tab_Design")
        self.label_19 = QtWidgets.QLabel(self.tab_Design)
        self.label_19.setGeometry(QtCore.QRect(21, 31, 101, 16))
        self.label_19.setObjectName("label_19")
        self.combo_design_method = QtWidgets.QComboBox(self.tab_Design)
        self.combo_design_method.setGeometry(QtCore.QRect(160, 31, 227, 22))
        self.combo_design_method.setObjectName("combo_design_method")
        self.combo_design_method.addItem("")
        self.combo_design_method.addItem("")
        self.combo_design_method.addItem("")
        self.tabWidget.addTab(self.tab_Design, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(DesignPreferences)
        self.tabWidget.setCurrentIndex(1)
        self.combo_slipfactor.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(DesignPreferences)

    def retranslateUi(self, DesignPreferences):
        _translate = QtCore.QCoreApplication.translate
        DesignPreferences.setWindowTitle(_translate("DesignPreferences", "Design preferences"))
        self.btn_defaults.setText(_translate("DesignPreferences", "Defaults"))
        self.btn_save.setText(_translate("DesignPreferences", "Save"))
        self.btn_close.setText(_translate("DesignPreferences", "Save"))
        self.label_31.setText(_translate("DesignPreferences", "Modulus of elasticity, E (GPa)"))
        self.label_28.setText(_translate("DesignPreferences", "Flange width, B (mm)*"))
        self.label_43.setText(_translate("DesignPreferences", "<html><head/><body><p>Plastic modulus, Z<span style=\" vertical-align:sub;\">pz</span> (cm<span style=\" vertical-align:super;\">3</span> )</p></body></html>"))
        self.label_48.setText(_translate("DesignPreferences", "Flange thickness, T (mm)*"))
        self.label_53.setText(_translate("DesignPreferences", "Mass, M (kg/m)"))
        self.pushButton_Add_Column.setText(_translate("DesignPreferences", "Add"))
        self.label_41.setText(_translate("DesignPreferences", "Type"))
        self.label_30.setText(_translate("DesignPreferences", "Designation"))
        self.label_42.setText(_translate("DesignPreferences", "<html><head/><body><p>Elastic modulus, Z<span style=\" vertical-align:sub;\">z</span> (cm<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.pushButton_Import_Column.setText(_translate("DesignPreferences", "Import xlsx file"))
        self.label_37.setText(_translate("DesignPreferences", "Modulus of rigidity, G (GPa)"))
        self.label_34.setText(_translate("DesignPreferences", "<html><head/><body><p>2nd Moment of area, I<span style=\" vertical-align:sub;\">z</span>(cm<span style=\" vertical-align:super;\">4</span>)</p></body></html>"))
        self.label_44.setText(_translate("DesignPreferences", "<html><head/><body><p>Elastic modulus, Z<span style=\" vertical-align:sub;\">y</span> (cm<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.label_49.setText(_translate("DesignPreferences", "Web thickness, t (mm)*"))
        self.label_51.setText(_translate("DesignPreferences", "<html><head/><body><p>Radius of gyration, r<span style=\" vertical-align:sub;\">z</span> (cm)</p></body></html>"))
        self.label_29.setText(_translate("DesignPreferences", "<html><head/><body><p>2nd Moment of area,I<span style=\" vertical-align:sub;\">y</span> (cm<span style=\" vertical-align:super;\">4</span>)</p></body></html>"))
        self.pushButton_Clear_Column.setText(_translate("DesignPreferences", "Clear"))
        self.pushButton_Download_Column.setText(_translate("DesignPreferences", "Download xlsx format"))
        self.label_47.setText(_translate("DesignPreferences", "<html><head/><body><p>Flange Slope, <span style=\" font-family:\'Symbol\'; font-size:large;\">a </span>(deg.)*</p></body></html>"))
        self.label_50.setText(_translate("DesignPreferences", "Root radius, R1 (mm)*"))
        self.label_35.setText(_translate("DesignPreferences", "Source"))
        self.label_52.setText(_translate("DesignPreferences", "Sectional Properties"))
        self.label_33.setText(_translate("DesignPreferences", "<html><head/><body><p>Radius of gyration, r<span style=\" vertical-align:sub;\">y</span> (cm)</p></body></html>"))
        self.label_45.setText(_translate("DesignPreferences", "Dimensions"))
        self.label_36.setText(_translate("DesignPreferences", "Toe radius, R2 (mm)*"))
        self.label_46.setText(_translate("DesignPreferences", "Ultimate strength, fu (MPa)"))
        self.label_54.setText(_translate("DesignPreferences", "Depth, D (mm)*"))
        self.label_32.setText(_translate("DesignPreferences", "Mechanical Properties"))
        self.label_55.setText(_translate("DesignPreferences", "Yield Strength , fy (MPa)"))
        self.label_56.setText(_translate("DesignPreferences", "<html><head/><body><p>Plastic modulus, Z<span style=\" vertical-align:sub;\">py</span> (cm<span style=\" vertical-align:super;\">3</span> )</p></body></html>"))
        self.label_57.setText(_translate("DesignPreferences", "<html><head/><body><p>Sectional area, a (cm<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.comboBox_Column.setItemText(0, _translate("DesignPreferences", "Rolled"))
        self.comboBox_Column.setItemText(1, _translate("DesignPreferences", "Welded"))
        self.label_85.setText(_translate("DesignPreferences", "Poissons ratio, v"))
        self.label_86.setText(_translate("DesignPreferences", "<html><head/><body><p>Thermal expansion </p><p>coeff.<span style=\" font-family:\'Symbol\'; font-size:large;\">a </span>(x10<span style=\" vertical-align:super;\">-6</span>/<span style=\" vertical-align:super;\">0</span>C)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Column), _translate("DesignPreferences", "Column"))
        self.label_58.setText(_translate("DesignPreferences", "Modulus of elasticity, E (GPa)"))
        self.label_59.setText(_translate("DesignPreferences", "Flange width, B (mm)*"))
        self.label_61.setText(_translate("DesignPreferences", "Flange thickness, T (mm)*"))
        self.label_62.setText(_translate("DesignPreferences", "Mass, M (kg/m)"))
        self.pushButton_Add_Beam.setText(_translate("DesignPreferences", "Add"))
        self.label_63.setText(_translate("DesignPreferences", "Type"))
        self.label_64.setText(_translate("DesignPreferences", "Designation"))
        self.pushButton_Import_Beam.setText(_translate("DesignPreferences", "Import xlsx file"))
        self.label_66.setText(_translate("DesignPreferences", "Modulus of rigidity, G (GPa)"))
        self.label_69.setText(_translate("DesignPreferences", "Web thickness, t (mm)*"))
        self.pushButton_Clear_Beam.setText(_translate("DesignPreferences", "Clear"))
        self.pushButton_Download_Beam.setText(_translate("DesignPreferences", "Download xlsx format"))
        self.label_73.setText(_translate("DesignPreferences", "Root radius, R1 (mm)*"))
        self.label_74.setText(_translate("DesignPreferences", "Source"))
        self.label_75.setText(_translate("DesignPreferences", "Sectional Properties"))
        self.label_77.setText(_translate("DesignPreferences", "Dimensions"))
        self.label_78.setText(_translate("DesignPreferences", "Toe radius, R2 (mm)*"))
        self.label_79.setText(_translate("DesignPreferences", "Ultimate strength, fu (MPa)"))
        self.label_80.setText(_translate("DesignPreferences", "Depth, D (mm)*"))
        self.label_81.setText(_translate("DesignPreferences", "Mechanical Properties"))
        self.label_82.setText(_translate("DesignPreferences", "Yield Strength , fy (MPa)"))
        self.comboBox_Beam.setItemText(0, _translate("DesignPreferences", "Rolled"))
        self.comboBox_Beam.setItemText(1, _translate("DesignPreferences", "Welded"))
        self.label_88.setText(_translate("DesignPreferences", "Poissons ratio, v"))
        self.label_89.setText(_translate("DesignPreferences", "<html><head/><body><p>Thermal expansion </p><p>coeff.<span style=\" font-family:\'Symbol\'; font-size:large;\">a </span>(x10<span style=\" vertical-align:super;\">-6</span>/<span style=\" vertical-align:super;\">0</span>C)</p></body></html>"))
        self.label_72.setText(_translate("DesignPreferences", "<html><head/><body><p>Flange Slope, <span style=\" font-family:\'Symbol\'; font-size:large;\">a </span>(deg.)*</p></body></html>"))
        self.label_145.setText(_translate("DesignPreferences", "<html><head/><body><p>Elastic modulus, Z<span style=\" vertical-align:sub;\">y</span> (cm<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.label_146.setText(_translate("DesignPreferences", "<html><head/><body><p>2nd Moment of area, I<span style=\" vertical-align:sub;\">z</span>(cm<span style=\" vertical-align:super;\">4</span>)</p></body></html>"))
        self.label_147.setText(_translate("DesignPreferences", "<html><head/><body><p>Sectional area, a (cm<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.label_148.setText(_translate("DesignPreferences", "<html><head/><body><p>Plastic modulus, Z<span style=\" vertical-align:sub;\">py</span> (cm<span style=\" vertical-align:super;\">3</span> )</p></body></html>"))
        self.label_149.setText(_translate("DesignPreferences", "<html><head/><body><p>2nd Moment of area,I<span style=\" vertical-align:sub;\">y</span> (cm<span style=\" vertical-align:super;\">4</span>)</p></body></html>"))
        self.label_150.setText(_translate("DesignPreferences", "<html><head/><body><p>Radius of gyration, r<span style=\" vertical-align:sub;\">z</span> (cm)</p></body></html>"))
        self.label_151.setText(_translate("DesignPreferences", "<html><head/><body><p>Elastic modulus, Z<span style=\" vertical-align:sub;\">z</span> (cm<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.label_152.setText(_translate("DesignPreferences", "<html><head/><body><p>Plastic modulus, Z<span style=\" vertical-align:sub;\">pz</span> (cm<span style=\" vertical-align:super;\">3</span> )</p></body></html>"))
        self.label_153.setText(_translate("DesignPreferences", "<html><head/><body><p>Radius of gyration, r<span style=\" vertical-align:sub;\">y</span> (cm)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Beam), _translate("DesignPreferences", "Beam"))
        self.label_note.setText(_translate("DesignPreferences", "NOTE : If slip is permitted under the design load, design the bolt as a bearing\n"
"bolt and select corresponding bolt grade."))
        self.label_3.setText(_translate("DesignPreferences", "Description"))
        self.textBrowser.setHtml(_translate("DesignPreferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td colspan=\"3\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">IS 800 Table 20 Typical Average Values for Coefficient of Friction (</span><span style=\" font-family:\'Calibri,sans-serif\'; font-size:9pt;\">µ</span><span style=\" font-family:\'Calibri,sans-serif\'; font-size:9pt; vertical-align:sub;\">f</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">)</span></p></td></tr></table>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td width=\"26\"></td>\n"
"<td width=\"383\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Treatment of Surfaces</span></p></td>\n"
"<td width=\"78\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  µ_f</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">i)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces not treated</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.2</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">ii)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with short or grit with any loose rust removed, no pitting</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.5</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">iii)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with short or grit and hot-dip galvanized</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.1</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">iv)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with short or grit and spray - metallized with zinc (thickness 50-70 µm)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.25</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">v)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with shot or grit and painted with ethylzinc silicate coat (thickness 30-60 µm)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.3</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">vi)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Sand blasted surface, after light rusting</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.52</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">vii)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with shot or grit and painted with ethylzinc silicate coat (thickness 60-80 µm)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.3</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">viii)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with shot or grit and painted with alcalizinc silicate coat (thickness 60-80 µm)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.3</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">ix)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Surfaces blasted with shot or grit and spray metallized with aluminium (thickness &gt;50 µm)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.5</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">x)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Clean mill scale</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.33</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">xi)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Sand blasted surface</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.48</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">xii)</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Red lead painted surface</span></p></td>\n"
"<td>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">  0.1</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></td></tr></table></body></html>"))
        self.label.setText(_translate("DesignPreferences", "Bolt type"))
        self.label_4.setText(_translate("DesignPreferences", "Material grade overwrite (MPa)"))
        self.label_2.setText(_translate("DesignPreferences", "Bolt hole type"))
        self.combo_boltHoleType.setItemText(0, _translate("DesignPreferences", "Standard"))
        self.combo_boltHoleType.setItemText(1, _translate("DesignPreferences", "Over-sized"))
        self.label_8.setText(_translate("DesignPreferences", "Fu"))
        self.txt_boltFu.setText(_translate("DesignPreferences", "800"))
        self.combo_boltType.setItemText(0, _translate("DesignPreferences", "Pretensioned"))
        self.combo_boltType.setItemText(1, _translate("DesignPreferences", "Non-pretensioned"))
        self.label_7.setText(_translate("DesignPreferences", "HSFG bolt design parameters:"))
        self.label_15.setText(_translate("DesignPreferences", "Slip factor (µ_f)"))
        self.combo_slipfactor.setItemText(0, _translate("DesignPreferences", "0.2"))
        self.combo_slipfactor.setItemText(1, _translate("DesignPreferences", "0.5"))
        self.combo_slipfactor.setItemText(2, _translate("DesignPreferences", "0.1"))
        self.combo_slipfactor.setItemText(3, _translate("DesignPreferences", "0.25"))
        self.combo_slipfactor.setItemText(4, _translate("DesignPreferences", "0.3"))
        self.combo_slipfactor.setItemText(5, _translate("DesignPreferences", "0.33"))
        self.combo_slipfactor.setItemText(6, _translate("DesignPreferences", "0.48"))
        self.combo_slipfactor.setItemText(7, _translate("DesignPreferences", "0.52"))
        self.combo_slipfactor.setItemText(8, _translate("DesignPreferences", "0.55"))
        self.label_5.setText(_translate("DesignPreferences", "Inputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Bolt), _translate("DesignPreferences", "Bolt"))
        self.label_16.setText(_translate("DesignPreferences", "Inputs"))
        self.label_17.setText(_translate("DesignPreferences", "Description"))
        self.textBrowser_weldDescription.setHtml(_translate("DesignPreferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Shop weld takes a material safety factor of 1.25</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Field weld takes a material safety factor of 1.5</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">(IS 800 - cl. 5. 4. 1 or Table 5)</span></p></body></html>"))
        self.label_6.setText(_translate("DesignPreferences", "Material grade overwrite (MPa)"))
        self.combo_weldType.setItemText(0, _translate("DesignPreferences", "Shop weld"))
        self.combo_weldType.setItemText(1, _translate("DesignPreferences", "Field weld"))
        self.label_22.setText(_translate("DesignPreferences", "Type of weld"))
        self.txt_weldFu.setText(_translate("DesignPreferences", "410"))
        self.label_10.setText(_translate("DesignPreferences", "Fu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Weld), _translate("DesignPreferences", "Weld"))
        self.label_38.setText(_translate("DesignPreferences", "Inputs"))
        self.label_39.setText(_translate("DesignPreferences", "Type of edges"))
        self.combo_detailingEdgeType.setItemText(0, _translate("DesignPreferences", "a - Sheared or hand flame cut"))
        self.combo_detailingEdgeType.setItemText(1, _translate("DesignPreferences", "b - Rolled, machine-flame cut, sawn and planed"))
        self.label_40.setText(_translate("DesignPreferences", "Are the members exposed to\n"
"corrosive influences?"))
        self.combo_detailing_memebers.setItemText(0, _translate("DesignPreferences", "No"))
        self.combo_detailing_memebers.setItemText(1, _translate("DesignPreferences", "Yes"))
        self.label_18.setText(_translate("DesignPreferences", "Description"))
        self.textBrowser_detailingDescription.setHtml(_translate("DesignPreferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">The minimum edge and end distances from the centre of any hole to the nearest edge of a plate shall not be less than </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">1.7</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> times the hole diameter in case of </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[a- sheared or hand flame cut edges] </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">and </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">1.5 </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">times the hole diameter in case of </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[b - Rolled, machine-flame cut, sawn and planed edges]</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> (IS 800 - cl. 10. 2. 4. 2)</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\'; font-size:8pt; vertical-align:middle;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">This gap should include the tolerance value of 5mm. So if the assumed clearance is 5mm, then the gap should be = 10mm (= 5mm {clearance} + 5 mm{tolerance})</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\'; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Specifying whether the members are exposed to corrosive influences, here, only affects the calculation of the maximum edge distance as per cl. 10.2.4.3</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Detailing), _translate("DesignPreferences", "Detailing"))
        self.label_19.setText(_translate("DesignPreferences", "Design Method"))
        self.combo_design_method.setItemText(0, _translate("DesignPreferences", "Limit State Design"))
        self.combo_design_method.setItemText(1, _translate("DesignPreferences", "Limit State (Capacity based) Design"))
        self.combo_design_method.setItemText(2, _translate("DesignPreferences", "Working Stress Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Design), _translate("DesignPreferences", "Design"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesignPreferences = QtWidgets.QDialog()
    ui = Ui_DesignPreferences()
    ui.setupUi(DesignPreferences)
    DesignPreferences.show()
    sys.exit(app.exec_())

