# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(966, 576)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_Designation = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Designation.setGeometry(QtCore.QRect(90, 30, 251, 25))
        self.lineEdit_Designation.setObjectName("lineEdit_Designation")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Type = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Type.setGeometry(QtCore.QRect(390, 30, 261, 25))
        self.lineEdit_Type.setObjectName("lineEdit_Type")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(660, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_Source = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Source.setGeometry(QtCore.QRect(710, 30, 241, 25))
        self.lineEdit_Source.setObjectName("lineEdit_Source")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(380, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(380, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_YieldStrength = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_YieldStrength.setGeometry(QtCore.QRect(210, 110, 113, 25))
        self.lineEdit_YieldStrength.setObjectName("lineEdit_YieldStrength")
        self.lineEdit_UltimateStrength = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_UltimateStrength.setGeometry(QtCore.QRect(210, 150, 113, 25))
        self.lineEdit_UltimateStrength.setObjectName("lineEdit_UltimateStrength")
        self.lineEdit_ModElasticity = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ModElasticity.setGeometry(QtCore.QRect(590, 110, 113, 25))
        self.lineEdit_ModElasticity.setObjectName("lineEdit_ModElasticity")
        self.lineEdit_PoissonsRatio = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_PoissonsRatio.setGeometry(QtCore.QRect(590, 150, 113, 25))
        self.lineEdit_PoissonsRatio.setObjectName("lineEdit_PoissonsRatio")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(10, 280, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(10, 310, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(10, 340, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(10, 370, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(10, 400, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_Depth = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Depth.setGeometry(QtCore.QRect(200, 220, 113, 25))
        self.lineEdit_Depth.setObjectName("lineEdit_Depth")
        self.lineEdit_FlangeWidth = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_FlangeWidth.setGeometry(QtCore.QRect(200, 250, 113, 25))
        self.lineEdit_FlangeWidth.setObjectName("lineEdit_FlangeWidth")
        self.lineEdit_FlangeThickness = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_FlangeThickness.setGeometry(QtCore.QRect(200, 280, 113, 25))
        self.lineEdit_FlangeThickness.setObjectName("lineEdit_FlangeThickness")
        self.lineEdit_WeBThickness = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_WeBThickness.setGeometry(QtCore.QRect(200, 310, 113, 25))
        self.lineEdit_WeBThickness.setObjectName("lineEdit_WeBThickness")
        self.lineEdit_FlangeSlope = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_FlangeSlope.setGeometry(QtCore.QRect(200, 340, 113, 25))
        self.lineEdit_FlangeSlope.setObjectName("lineEdit_FlangeSlope")
        self.lineEdit_RootRadius = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_RootRadius.setGeometry(QtCore.QRect(200, 370, 113, 25))
        self.lineEdit_RootRadius.setObjectName("lineEdit_RootRadius")
        self.lineEdit_ToeRadius = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ToeRadius.setGeometry(QtCore.QRect(200, 400, 113, 25))
        self.lineEdit_ToeRadius.setObjectName("lineEdit_ToeRadius")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(330, 190, 21, 331))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(370, 369, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_SectionalArea = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_SectionalArea.setGeometry(QtCore.QRect(580, 250, 111, 25))
        self.lineEdit_SectionalArea.setObjectName("lineEdit_SectionalArea")
        self.lineEdit_MomentOfAreaZ = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_MomentOfAreaZ.setGeometry(QtCore.QRect(580, 280, 111, 25))
        self.lineEdit_MomentOfAreaZ.setObjectName("lineEdit_MomentOfAreaZ")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(370, 339, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(370, 399, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_ElasticModZ = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ElasticModZ.setGeometry(QtCore.QRect(580, 400, 111, 25))
        self.lineEdit_ElasticModZ.setObjectName("lineEdit_ElasticModZ")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(370, 249, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_RogZ = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_RogZ.setGeometry(QtCore.QRect(580, 340, 111, 25))
        self.lineEdit_RogZ.setObjectName("lineEdit_RogZ")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(370, 279, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_RogY = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_RogY.setGeometry(QtCore.QRect(580, 370, 111, 25))
        self.lineEdit_RogY.setObjectName("lineEdit_RogY")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(370, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(370, 219, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_MomentOfAreaY = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_MomentOfAreaY.setGeometry(QtCore.QRect(580, 310, 111, 25))
        self.lineEdit_MomentOfAreaY.setObjectName("lineEdit_MomentOfAreaY")
        self.lineEdit_Mass = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Mass.setGeometry(QtCore.QRect(580, 220, 111, 25))
        self.lineEdit_Mass.setObjectName("lineEdit_Mass")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(370, 309, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(370, 459, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_ElasticModY = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ElasticModY.setGeometry(QtCore.QRect(580, 430, 111, 25))
        self.lineEdit_ElasticModY.setObjectName("lineEdit_ElasticModY")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(370, 489, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_ElasticModPZ = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ElasticModPZ.setGeometry(QtCore.QRect(580, 460, 111, 25))
        self.lineEdit_ElasticModPZ.setObjectName("lineEdit_ElasticModPZ")
        self.lineEdit_ElasticModPY = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ElasticModPY.setGeometry(QtCore.QRect(580, 490, 111, 25))
        self.lineEdit_ElasticModPY.setObjectName("lineEdit_ElasticModPY")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(370, 429, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(683, 190, 61, 331))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 510, 971, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_Clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_Clear.setGeometry(QtCore.QRect(50, 540, 89, 25))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_Add = QtWidgets.QPushButton(Dialog)
        self.pushButton_Add.setGeometry(QtCore.QRect(190, 540, 89, 25))
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_Download = QtWidgets.QPushButton(Dialog)
        self.pushButton_Download.setGeometry(QtCore.QRect(598, 540, 171, 25))
        self.pushButton_Download.setObjectName("pushButton_Download")
        self.pushButton_Import = QtWidgets.QPushButton(Dialog)
        self.pushButton_Import.setGeometry(QtCore.QRect(808, 540, 121, 25))
        self.pushButton_Import.setObjectName("pushButton_Import")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Designation"))
        self.label_2.setText(_translate("Dialog", "Type"))
        self.label_3.setText(_translate("Dialog", "Source"))
        self.label_5.setText(_translate("Dialog", "Yield Strength , fy (MPa)"))
        self.label_4.setText(_translate("Dialog", "Mechanical Properties"))
        self.label_6.setText(_translate("Dialog", "Ultimate strength, fu (MPa)"))
        self.label_7.setText(_translate("Dialog", "Modulus of elasticity, E (MPa)"))
        self.label_8.setText(_translate("Dialog", "Poissons ratio, v"))
        self.label_9.setText(_translate("Dialog", "Dimensions"))
        self.label_10.setText(_translate("Dialog", "Depth, D (mm)"))
        self.label_11.setText(_translate("Dialog", "Flange width, B (mm)"))
        self.label_12.setText(_translate("Dialog", "Flange thickness, T (mm)"))
        self.label_13.setText(_translate("Dialog", "Web thickness, t (mm)"))
        self.label_14.setText(_translate("Dialog", "Flange slope, (deg.)"))
        self.label_15.setText(_translate("Dialog", "Root radius, R1 (mm)"))
        self.label_16.setText(_translate("Dialog", "Toe radius, R2 (mm)"))
        self.label_17.setText(_translate("Dialog", "Radius of gyration, ry (cm2)"))
        self.label_18.setText(_translate("Dialog", "Radius of gyration, rz (cm2)"))
        self.label_19.setText(_translate("Dialog", "Elastic modulus, Zz (cm2)"))
        self.label_20.setText(_translate("Dialog", "Sectional area, a (mm )"))
        self.label_21.setText(_translate("Dialog", "2nd Moment of area, Iz(cm2)"))
        self.label_22.setText(_translate("Dialog", "Sectional Properties"))
        self.label_23.setText(_translate("Dialog", "Mass, M (kg/m)"))
        self.label_24.setText(_translate("Dialog", "2nd Moment of area, Iy (cm2)"))
        self.label_25.setText(_translate("Dialog", "Plastic modulus, Zpz (cm2 )"))
        self.label_26.setText(_translate("Dialog", "Plastic modulus, Zpy (cm2 )"))
        self.label_27.setText(_translate("Dialog", "Elastic modulus, Zy (cm2)"))
        self.pushButton_Clear.setText(_translate("Dialog", "Clear"))
        self.pushButton_Add.setText(_translate("Dialog", "Add"))
        self.pushButton_Download.setText(_translate("Dialog", "Download xlsx format"))
        self.pushButton_Import.setText(_translate("Dialog", "Import xlsx file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

