# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stiffener.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stiffener(object):
    def setupUi(self, Stiffener):
        Stiffener.setObjectName("Stiffener")
        Stiffener.resize(246, 238)
        self.gridLayout = QtWidgets.QGridLayout(Stiffener)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.txt_stiffnrLength = QtWidgets.QLineEdit(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_stiffnrLength.setFont(font)
        self.txt_stiffnrLength.setReadOnly(True)
        self.txt_stiffnrLength.setObjectName("txt_stiffnrLength")
        self.gridLayout.addWidget(self.txt_stiffnrLength, 2, 1, 1, 1)
        self.txt_stiffnrWeldSize = QtWidgets.QLineEdit(Stiffener)
        self.txt_stiffnrWeldSize.setObjectName("txt_stiffnrWeldSize")
        self.gridLayout.addWidget(self.txt_stiffnrWeldSize, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.txt_stiffnrNotchAtBottom = QtWidgets.QLineEdit(Stiffener)
        self.txt_stiffnrNotchAtBottom.setObjectName("txt_stiffnrNotchAtBottom")
        self.gridLayout.addWidget(self.txt_stiffnrNotchAtBottom, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.txt_stiffnrHeight = QtWidgets.QLineEdit(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_stiffnrHeight.setFont(font)
        self.txt_stiffnrHeight.setReadOnly(True)
        self.txt_stiffnrHeight.setObjectName("txt_stiffnrHeight")
        self.gridLayout.addWidget(self.txt_stiffnrHeight, 1, 1, 1, 1)
        self.txt_stiffnrNotchAtTop = QtWidgets.QLineEdit(Stiffener)
        self.txt_stiffnrNotchAtTop.setObjectName("txt_stiffnrNotchAtTop")
        self.gridLayout.addWidget(self.txt_stiffnrNotchAtTop, 5, 1, 1, 1)
        self.txt_stiffnrThickness = QtWidgets.QLineEdit(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_stiffnrThickness.setFont(font)
        self.txt_stiffnrThickness.setReadOnly(True)
        self.txt_stiffnrThickness.setObjectName("txt_stiffnrThickness")
        self.gridLayout.addWidget(self.txt_stiffnrThickness, 3, 1, 1, 1)
        self.plateHeight = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight.setFont(font)
        self.plateHeight.setObjectName("plateHeight")
        self.gridLayout.addWidget(self.plateHeight, 1, 0, 1, 1)
        self.label_163 = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_163.setObjectName("label_163")
        self.gridLayout.addWidget(self.label_163, 3, 0, 1, 1)
        self.txt_stiffnrNo = QtWidgets.QLineEdit(Stiffener)
        self.txt_stiffnrNo.setObjectName("txt_stiffnrNo")
        self.gridLayout.addWidget(self.txt_stiffnrNo, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Stiffener)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)

        self.retranslateUi(Stiffener)
        QtCore.QMetaObject.connectSlotsByName(Stiffener)

    def retranslateUi(self, Stiffener):
        _translate = QtCore.QCoreApplication.translate
        Stiffener.setWindowTitle(_translate("Stiffener", "Stiffener"))
        self.label.setText(_translate("Stiffener", "Weld Size (mm)"))
        self.label_2.setText(_translate("Stiffener", "Length (mm)"))
        self.label_4.setText(_translate("Stiffener", "Notch at Bottom (mm)"))
        self.label_3.setText(_translate("Stiffener", "Notch at Top (mm)"))
        self.plateHeight.setText(_translate("Stiffener", "Height (mm)"))
        self.label_163.setText(_translate("Stiffener", "<html><head/><body><p>Thickness (mm)</p></body></html>"))
        self.label_5.setText(_translate("Stiffener", "Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Stiffener = QtWidgets.QDialog()
    ui = Ui_Stiffener()
    ui.setupUi(Stiffener)
    Stiffener.show()
    sys.exit(app.exec_())

